// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddItemToInventoryArgs {
    pub player_id: u32,
    pub item_id: String,
    pub quantity: i32,
}

impl From<AddItemToInventoryArgs> for super::Reducer {
    fn from(args: AddItemToInventoryArgs) -> Self {
        Self::AddItemToInventory {
            player_id: args.player_id,
            item_id: args.item_id,
            quantity: args.quantity,
        }
    }
}

impl __sdk::InModule for AddItemToInventoryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_item_to_inventory`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_item_to_inventory {
    /// Request that the remote module invoke the reducer `add_item_to_inventory` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_item_to_inventory:add_item_to_inventory_then`] to run a callback after the reducer completes.
    fn add_item_to_inventory(
        &self,
        player_id: u32,
        item_id: String,
        quantity: i32,
    ) -> __sdk::Result<()> {
        self.add_item_to_inventory_then(player_id, item_id, quantity, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_item_to_inventory` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_item_to_inventory_then(
        &self,
        player_id: u32,
        item_id: String,
        quantity: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_item_to_inventory for super::RemoteReducers {
    fn add_item_to_inventory_then(
        &self,
        player_id: u32,
        item_id: String,
        quantity: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AddItemToInventoryArgs {
                player_id,
                item_id,
                quantity,
            },
            callback,
        )
    }
}
