// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ApplyDamageToPlayerArgs {
    pub player_id: u32,
    pub damage: f32,
    pub attacker_id: u32,
}

impl From<ApplyDamageToPlayerArgs> for super::Reducer {
    fn from(args: ApplyDamageToPlayerArgs) -> Self {
        Self::ApplyDamageToPlayer {
            player_id: args.player_id,
            damage: args.damage,
            attacker_id: args.attacker_id,
        }
    }
}

impl __sdk::InModule for ApplyDamageToPlayerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `apply_damage_to_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait apply_damage_to_player {
    /// Request that the remote module invoke the reducer `apply_damage_to_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`apply_damage_to_player:apply_damage_to_player_then`] to run a callback after the reducer completes.
    fn apply_damage_to_player(
        &self,
        player_id: u32,
        damage: f32,
        attacker_id: u32,
    ) -> __sdk::Result<()> {
        self.apply_damage_to_player_then(player_id, damage, attacker_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `apply_damage_to_player` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn apply_damage_to_player_then(
        &self,
        player_id: u32,
        damage: f32,
        attacker_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl apply_damage_to_player for super::RemoteReducers {
    fn apply_damage_to_player_then(
        &self,
        player_id: u32,
        damage: f32,
        attacker_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ApplyDamageToPlayerArgs {
                player_id,
                damage,
                attacker_id,
            },
            callback,
        )
    }
}
