// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CombatEvent {
    pub id: u32,
    pub attacker_id: u32,
    pub target_id: u32,
    pub weapon_type: String,
    pub damage: f32,
    pub timestamp: u64,
}

impl __sdk::InModule for CombatEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CombatEvent`.
///
/// Provides typed access to columns for query building.
pub struct CombatEventCols {
    pub id: __sdk::__query_builder::Col<CombatEvent, u32>,
    pub attacker_id: __sdk::__query_builder::Col<CombatEvent, u32>,
    pub target_id: __sdk::__query_builder::Col<CombatEvent, u32>,
    pub weapon_type: __sdk::__query_builder::Col<CombatEvent, String>,
    pub damage: __sdk::__query_builder::Col<CombatEvent, f32>,
    pub timestamp: __sdk::__query_builder::Col<CombatEvent, u64>,
}

impl __sdk::__query_builder::HasCols for CombatEvent {
    type Cols = CombatEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CombatEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            attacker_id: __sdk::__query_builder::Col::new(table_name, "attacker_id"),
            target_id: __sdk::__query_builder::Col::new(table_name, "target_id"),
            weapon_type: __sdk::__query_builder::Col::new(table_name, "weapon_type"),
            damage: __sdk::__query_builder::Col::new(table_name, "damage"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
        }
    }
}

/// Indexed column accessor struct for the table `CombatEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct CombatEventIxCols {
    pub id: __sdk::__query_builder::IxCol<CombatEvent, u32>,
}

impl __sdk::__query_builder::HasIxCols for CombatEvent {
    type IxCols = CombatEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CombatEventIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CombatEvent {}
