// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ContainerItem {
    pub id: u32,
    pub container_id: u32,
    pub item_id: String,
    pub quantity: i32,
    pub slot: u32,
}

impl __sdk::InModule for ContainerItem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ContainerItem`.
///
/// Provides typed access to columns for query building.
pub struct ContainerItemCols {
    pub id: __sdk::__query_builder::Col<ContainerItem, u32>,
    pub container_id: __sdk::__query_builder::Col<ContainerItem, u32>,
    pub item_id: __sdk::__query_builder::Col<ContainerItem, String>,
    pub quantity: __sdk::__query_builder::Col<ContainerItem, i32>,
    pub slot: __sdk::__query_builder::Col<ContainerItem, u32>,
}

impl __sdk::__query_builder::HasCols for ContainerItem {
    type Cols = ContainerItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ContainerItemCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            container_id: __sdk::__query_builder::Col::new(table_name, "container_id"),
            item_id: __sdk::__query_builder::Col::new(table_name, "item_id"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            slot: __sdk::__query_builder::Col::new(table_name, "slot"),
        }
    }
}

/// Indexed column accessor struct for the table `ContainerItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct ContainerItemIxCols {
    pub id: __sdk::__query_builder::IxCol<ContainerItem, u32>,
}

impl __sdk::__query_builder::HasIxCols for ContainerItem {
    type IxCols = ContainerItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ContainerItemIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ContainerItem {}
