// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Container {
    pub id: u32,
    pub map_id: String,
    pub position_x: f32,
    pub position_y: f32,
    pub capacity: u32,
    pub label: String,
}

impl __sdk::InModule for Container {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Container`.
///
/// Provides typed access to columns for query building.
pub struct ContainerCols {
    pub id: __sdk::__query_builder::Col<Container, u32>,
    pub map_id: __sdk::__query_builder::Col<Container, String>,
    pub position_x: __sdk::__query_builder::Col<Container, f32>,
    pub position_y: __sdk::__query_builder::Col<Container, f32>,
    pub capacity: __sdk::__query_builder::Col<Container, u32>,
    pub label: __sdk::__query_builder::Col<Container, String>,
}

impl __sdk::__query_builder::HasCols for Container {
    type Cols = ContainerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ContainerCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
            position_x: __sdk::__query_builder::Col::new(table_name, "position_x"),
            position_y: __sdk::__query_builder::Col::new(table_name, "position_y"),
            capacity: __sdk::__query_builder::Col::new(table_name, "capacity"),
            label: __sdk::__query_builder::Col::new(table_name, "label"),
        }
    }
}

/// Indexed column accessor struct for the table `Container`.
///
/// Provides typed access to indexed columns for query building.
pub struct ContainerIxCols {
    pub id: __sdk::__query_builder::IxCol<Container, u32>,
}

impl __sdk::__query_builder::HasIxCols for Container {
    type IxCols = ContainerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ContainerIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Container {}
