// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateProjectileArgs {
    pub player_id: u32,
    pub origin_x: f32,
    pub origin_y: f32,
    pub direction_x: f32,
    pub direction_y: f32,
}

impl From<CreateProjectileArgs> for super::Reducer {
    fn from(args: CreateProjectileArgs) -> Self {
        Self::CreateProjectile {
            player_id: args.player_id,
            origin_x: args.origin_x,
            origin_y: args.origin_y,
            direction_x: args.direction_x,
            direction_y: args.direction_y,
        }
    }
}

impl __sdk::InModule for CreateProjectileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_projectile`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_projectile {
    /// Request that the remote module invoke the reducer `create_projectile` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_projectile:create_projectile_then`] to run a callback after the reducer completes.
    fn create_projectile(
        &self,
        player_id: u32,
        origin_x: f32,
        origin_y: f32,
        direction_x: f32,
        direction_y: f32,
    ) -> __sdk::Result<()> {
        self.create_projectile_then(
            player_id,
            origin_x,
            origin_y,
            direction_x,
            direction_y,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_projectile` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_projectile_then(
        &self,
        player_id: u32,
        origin_x: f32,
        origin_y: f32,
        direction_x: f32,
        direction_y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_projectile for super::RemoteReducers {
    fn create_projectile_then(
        &self,
        player_id: u32,
        origin_x: f32,
        origin_y: f32,
        direction_x: f32,
        direction_y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateProjectileArgs {
                player_id,
                origin_x,
                origin_y,
                direction_x,
                direction_y,
            },
            callback,
        )
    }
}
