// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateInteractableObjectArgs {
    pub object_type: String,
    pub position_x: f32,
    pub position_y: f32,
    pub map_id: String,
}

impl From<CreateInteractableObjectArgs> for super::Reducer {
    fn from(args: CreateInteractableObjectArgs) -> Self {
        Self::CreateInteractableObject {
            object_type: args.object_type,
            position_x: args.position_x,
            position_y: args.position_y,
            map_id: args.map_id,
        }
    }
}

impl __sdk::InModule for CreateInteractableObjectArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_interactable_object`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_interactable_object {
    /// Request that the remote module invoke the reducer `create_interactable_object` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_interactable_object:create_interactable_object_then`] to run a callback after the reducer completes.
    fn create_interactable_object(
        &self,
        object_type: String,
        position_x: f32,
        position_y: f32,
        map_id: String,
    ) -> __sdk::Result<()> {
        self.create_interactable_object_then(object_type, position_x, position_y, map_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_interactable_object` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_interactable_object_then(
        &self,
        object_type: String,
        position_x: f32,
        position_y: f32,
        map_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_interactable_object for super::RemoteReducers {
    fn create_interactable_object_then(
        &self,
        object_type: String,
        position_x: f32,
        position_y: f32,
        map_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateInteractableObjectArgs {
                object_type,
                position_x,
                position_y,
                map_id,
            },
            callback,
        )
    }
}
