// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DepositItemArgs {
    pub container_id: u32,
    pub item_id: String,
    pub quantity: i32,
}

impl From<DepositItemArgs> for super::Reducer {
    fn from(args: DepositItemArgs) -> Self {
        Self::DepositItem {
            container_id: args.container_id,
            item_id: args.item_id,
            quantity: args.quantity,
        }
    }
}

impl __sdk::InModule for DepositItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `deposit_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait deposit_item {
    /// Request that the remote module invoke the reducer `deposit_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`deposit_item:deposit_item_then`] to run a callback after the reducer completes.
    fn deposit_item(&self, container_id: u32, item_id: String, quantity: i32) -> __sdk::Result<()> {
        self.deposit_item_then(container_id, item_id, quantity, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `deposit_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn deposit_item_then(
        &self,
        container_id: u32,
        item_id: String,
        quantity: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl deposit_item for super::RemoteReducers {
    fn deposit_item_then(
        &self,
        container_id: u32,
        item_id: String,
        quantity: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DepositItemArgs {
                container_id,
                item_id,
                quantity,
            },
            callback,
        )
    }
}
