// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Enemy {
    pub id: u32,
    pub position_x: f32,
    pub position_y: f32,
    pub velocity_x: f32,
    pub velocity_y: f32,
    pub health: f32,
    pub max_health: f32,
    pub enemy_type: String,
    pub map_id: String,
    pub state: String,
    pub patrol_center_x: f32,
    pub patrol_center_y: f32,
    pub patrol_radius: f32,
    pub detection_range: f32,
    pub leash_range: f32,
    pub target_player_id: Option<u32>,
    pub target_map_id: Option<String>,
    pub last_known_player_x: f32,
    pub last_known_player_y: f32,
    pub state_timer: f32,
    pub movement_speed: f32,
    pub attack_damage: f32,
    pub attack_range: f32,
    pub attack_cooldown: f32,
    pub last_attack_time: f64,
    pub is_active: bool,
}

impl __sdk::InModule for Enemy {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Enemy`.
///
/// Provides typed access to columns for query building.
pub struct EnemyCols {
    pub id: __sdk::__query_builder::Col<Enemy, u32>,
    pub position_x: __sdk::__query_builder::Col<Enemy, f32>,
    pub position_y: __sdk::__query_builder::Col<Enemy, f32>,
    pub velocity_x: __sdk::__query_builder::Col<Enemy, f32>,
    pub velocity_y: __sdk::__query_builder::Col<Enemy, f32>,
    pub health: __sdk::__query_builder::Col<Enemy, f32>,
    pub max_health: __sdk::__query_builder::Col<Enemy, f32>,
    pub enemy_type: __sdk::__query_builder::Col<Enemy, String>,
    pub map_id: __sdk::__query_builder::Col<Enemy, String>,
    pub state: __sdk::__query_builder::Col<Enemy, String>,
    pub patrol_center_x: __sdk::__query_builder::Col<Enemy, f32>,
    pub patrol_center_y: __sdk::__query_builder::Col<Enemy, f32>,
    pub patrol_radius: __sdk::__query_builder::Col<Enemy, f32>,
    pub detection_range: __sdk::__query_builder::Col<Enemy, f32>,
    pub leash_range: __sdk::__query_builder::Col<Enemy, f32>,
    pub target_player_id: __sdk::__query_builder::Col<Enemy, Option<u32>>,
    pub target_map_id: __sdk::__query_builder::Col<Enemy, Option<String>>,
    pub last_known_player_x: __sdk::__query_builder::Col<Enemy, f32>,
    pub last_known_player_y: __sdk::__query_builder::Col<Enemy, f32>,
    pub state_timer: __sdk::__query_builder::Col<Enemy, f32>,
    pub movement_speed: __sdk::__query_builder::Col<Enemy, f32>,
    pub attack_damage: __sdk::__query_builder::Col<Enemy, f32>,
    pub attack_range: __sdk::__query_builder::Col<Enemy, f32>,
    pub attack_cooldown: __sdk::__query_builder::Col<Enemy, f32>,
    pub last_attack_time: __sdk::__query_builder::Col<Enemy, f64>,
    pub is_active: __sdk::__query_builder::Col<Enemy, bool>,
}

impl __sdk::__query_builder::HasCols for Enemy {
    type Cols = EnemyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EnemyCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            position_x: __sdk::__query_builder::Col::new(table_name, "position_x"),
            position_y: __sdk::__query_builder::Col::new(table_name, "position_y"),
            velocity_x: __sdk::__query_builder::Col::new(table_name, "velocity_x"),
            velocity_y: __sdk::__query_builder::Col::new(table_name, "velocity_y"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
            max_health: __sdk::__query_builder::Col::new(table_name, "max_health"),
            enemy_type: __sdk::__query_builder::Col::new(table_name, "enemy_type"),
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            patrol_center_x: __sdk::__query_builder::Col::new(table_name, "patrol_center_x"),
            patrol_center_y: __sdk::__query_builder::Col::new(table_name, "patrol_center_y"),
            patrol_radius: __sdk::__query_builder::Col::new(table_name, "patrol_radius"),
            detection_range: __sdk::__query_builder::Col::new(table_name, "detection_range"),
            leash_range: __sdk::__query_builder::Col::new(table_name, "leash_range"),
            target_player_id: __sdk::__query_builder::Col::new(table_name, "target_player_id"),
            target_map_id: __sdk::__query_builder::Col::new(table_name, "target_map_id"),
            last_known_player_x: __sdk::__query_builder::Col::new(
                table_name,
                "last_known_player_x",
            ),
            last_known_player_y: __sdk::__query_builder::Col::new(
                table_name,
                "last_known_player_y",
            ),
            state_timer: __sdk::__query_builder::Col::new(table_name, "state_timer"),
            movement_speed: __sdk::__query_builder::Col::new(table_name, "movement_speed"),
            attack_damage: __sdk::__query_builder::Col::new(table_name, "attack_damage"),
            attack_range: __sdk::__query_builder::Col::new(table_name, "attack_range"),
            attack_cooldown: __sdk::__query_builder::Col::new(table_name, "attack_cooldown"),
            last_attack_time: __sdk::__query_builder::Col::new(table_name, "last_attack_time"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
        }
    }
}

/// Indexed column accessor struct for the table `Enemy`.
///
/// Provides typed access to indexed columns for query building.
pub struct EnemyIxCols {
    pub id: __sdk::__query_builder::IxCol<Enemy, u32>,
}

impl __sdk::__query_builder::HasIxCols for Enemy {
    type IxCols = EnemyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EnemyIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Enemy {}
