// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EnemyTransitionMapArgs {
    pub enemy_id: u32,
    pub destination_map_id: String,
    pub spawn_x: f32,
    pub spawn_y: f32,
}

impl From<EnemyTransitionMapArgs> for super::Reducer {
    fn from(args: EnemyTransitionMapArgs) -> Self {
        Self::EnemyTransitionMap {
            enemy_id: args.enemy_id,
            destination_map_id: args.destination_map_id,
            spawn_x: args.spawn_x,
            spawn_y: args.spawn_y,
        }
    }
}

impl __sdk::InModule for EnemyTransitionMapArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `enemy_transition_map`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait enemy_transition_map {
    /// Request that the remote module invoke the reducer `enemy_transition_map` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`enemy_transition_map:enemy_transition_map_then`] to run a callback after the reducer completes.
    fn enemy_transition_map(
        &self,
        enemy_id: u32,
        destination_map_id: String,
        spawn_x: f32,
        spawn_y: f32,
    ) -> __sdk::Result<()> {
        self.enemy_transition_map_then(enemy_id, destination_map_id, spawn_x, spawn_y, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `enemy_transition_map` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn enemy_transition_map_then(
        &self,
        enemy_id: u32,
        destination_map_id: String,
        spawn_x: f32,
        spawn_y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl enemy_transition_map for super::RemoteReducers {
    fn enemy_transition_map_then(
        &self,
        enemy_id: u32,
        destination_map_id: String,
        spawn_x: f32,
        spawn_y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            EnemyTransitionMapArgs {
                enemy_id,
                destination_map_id,
                spawn_x,
                spawn_y,
            },
            callback,
        )
    }
}
