// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ExecuteContextualActionArgs {
    pub player_id: u32,
    pub object_id: u32,
    pub action_type: String,
}

impl From<ExecuteContextualActionArgs> for super::Reducer {
    fn from(args: ExecuteContextualActionArgs) -> Self {
        Self::ExecuteContextualAction {
            player_id: args.player_id,
            object_id: args.object_id,
            action_type: args.action_type,
        }
    }
}

impl __sdk::InModule for ExecuteContextualActionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `execute_contextual_action`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait execute_contextual_action {
    /// Request that the remote module invoke the reducer `execute_contextual_action` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`execute_contextual_action:execute_contextual_action_then`] to run a callback after the reducer completes.
    fn execute_contextual_action(
        &self,
        player_id: u32,
        object_id: u32,
        action_type: String,
    ) -> __sdk::Result<()> {
        self.execute_contextual_action_then(player_id, object_id, action_type, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `execute_contextual_action` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn execute_contextual_action_then(
        &self,
        player_id: u32,
        object_id: u32,
        action_type: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl execute_contextual_action for super::RemoteReducers {
    fn execute_contextual_action_then(
        &self,
        player_id: u32,
        object_id: u32,
        action_type: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ExecuteContextualActionArgs {
                player_id,
                object_id,
                action_type,
            },
            callback,
        )
    }
}
