// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ExecuteAttackArgs {
    pub player_id: u32,
    pub weapon_type: String,
    pub direction_x: f32,
    pub direction_y: f32,
}

impl From<ExecuteAttackArgs> for super::Reducer {
    fn from(args: ExecuteAttackArgs) -> Self {
        Self::ExecuteAttack {
            player_id: args.player_id,
            weapon_type: args.weapon_type,
            direction_x: args.direction_x,
            direction_y: args.direction_y,
        }
    }
}

impl __sdk::InModule for ExecuteAttackArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `execute_attack`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait execute_attack {
    /// Request that the remote module invoke the reducer `execute_attack` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`execute_attack:execute_attack_then`] to run a callback after the reducer completes.
    fn execute_attack(
        &self,
        player_id: u32,
        weapon_type: String,
        direction_x: f32,
        direction_y: f32,
    ) -> __sdk::Result<()> {
        self.execute_attack_then(player_id, weapon_type, direction_x, direction_y, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `execute_attack` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn execute_attack_then(
        &self,
        player_id: u32,
        weapon_type: String,
        direction_x: f32,
        direction_y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl execute_attack for super::RemoteReducers {
    fn execute_attack_then(
        &self,
        player_id: u32,
        weapon_type: String,
        direction_x: f32,
        direction_y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ExecuteAttackArgs {
                player_id,
                weapon_type,
                direction_x,
                direction_y,
            },
            callback,
        )
    }
}
