// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ForcePlayerPositionArgs {
    pub player_id: u32,
    pub x: f32,
    pub y: f32,
}

impl From<ForcePlayerPositionArgs> for super::Reducer {
    fn from(args: ForcePlayerPositionArgs) -> Self {
        Self::ForcePlayerPosition {
            player_id: args.player_id,
            x: args.x,
            y: args.y,
        }
    }
}

impl __sdk::InModule for ForcePlayerPositionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `force_player_position`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait force_player_position {
    /// Request that the remote module invoke the reducer `force_player_position` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`force_player_position:force_player_position_then`] to run a callback after the reducer completes.
    fn force_player_position(&self, player_id: u32, x: f32, y: f32) -> __sdk::Result<()> {
        self.force_player_position_then(player_id, x, y, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `force_player_position` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn force_player_position_then(
        &self,
        player_id: u32,
        x: f32,
        y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl force_player_position for super::RemoteReducers {
    fn force_player_position_then(
        &self,
        player_id: u32,
        x: f32,
        y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ForcePlayerPositionArgs { player_id, x, y }, callback)
    }
}
