// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GetResourceByIdArgs {
    pub resource_id: u32,
}

impl From<GetResourceByIdArgs> for super::Reducer {
    fn from(args: GetResourceByIdArgs) -> Self {
        Self::GetResourceById {
            resource_id: args.resource_id,
        }
    }
}

impl __sdk::InModule for GetResourceByIdArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `get_resource_by_id`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait get_resource_by_id {
    /// Request that the remote module invoke the reducer `get_resource_by_id` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`get_resource_by_id:get_resource_by_id_then`] to run a callback after the reducer completes.
    fn get_resource_by_id(&self, resource_id: u32) -> __sdk::Result<()> {
        self.get_resource_by_id_then(resource_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `get_resource_by_id` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn get_resource_by_id_then(
        &self,
        resource_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl get_resource_by_id for super::RemoteReducers {
    fn get_resource_by_id_then(
        &self,
        resource_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GetResourceByIdArgs { resource_id }, callback)
    }
}
