// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GetPlayerPositionArgs {
    pub player_id: u32,
}

impl From<GetPlayerPositionArgs> for super::Reducer {
    fn from(args: GetPlayerPositionArgs) -> Self {
        Self::GetPlayerPosition {
            player_id: args.player_id,
        }
    }
}

impl __sdk::InModule for GetPlayerPositionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `get_player_position`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait get_player_position {
    /// Request that the remote module invoke the reducer `get_player_position` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`get_player_position:get_player_position_then`] to run a callback after the reducer completes.
    fn get_player_position(&self, player_id: u32) -> __sdk::Result<()> {
        self.get_player_position_then(player_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `get_player_position` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn get_player_position_then(
        &self,
        player_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl get_player_position for super::RemoteReducers {
    fn get_player_position_then(
        &self,
        player_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GetPlayerPositionArgs { player_id }, callback)
    }
}
