// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GetMapDataArgs {
    pub map_id: String,
}

impl From<GetMapDataArgs> for super::Reducer {
    fn from(args: GetMapDataArgs) -> Self {
        Self::GetMapData {
            map_id: args.map_id,
        }
    }
}

impl __sdk::InModule for GetMapDataArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `get_map_data`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait get_map_data {
    /// Request that the remote module invoke the reducer `get_map_data` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`get_map_data:get_map_data_then`] to run a callback after the reducer completes.
    fn get_map_data(&self, map_id: String) -> __sdk::Result<()> {
        self.get_map_data_then(map_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `get_map_data` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn get_map_data_then(
        &self,
        map_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl get_map_data for super::RemoteReducers {
    fn get_map_data_then(
        &self,
        map_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GetMapDataArgs { map_id }, callback)
    }
}
