// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GetProjectilesInMapArgs {
    pub map_id: String,
}

impl From<GetProjectilesInMapArgs> for super::Reducer {
    fn from(args: GetProjectilesInMapArgs) -> Self {
        Self::GetProjectilesInMap {
            map_id: args.map_id,
        }
    }
}

impl __sdk::InModule for GetProjectilesInMapArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `get_projectiles_in_map`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait get_projectiles_in_map {
    /// Request that the remote module invoke the reducer `get_projectiles_in_map` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`get_projectiles_in_map:get_projectiles_in_map_then`] to run a callback after the reducer completes.
    fn get_projectiles_in_map(&self, map_id: String) -> __sdk::Result<()> {
        self.get_projectiles_in_map_then(map_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `get_projectiles_in_map` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn get_projectiles_in_map_then(
        &self,
        map_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl get_projectiles_in_map for super::RemoteReducers {
    fn get_projectiles_in_map_then(
        &self,
        map_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GetProjectilesInMapArgs { map_id }, callback)
    }
}
