// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GiveArrowsToPlayerArgs {
    pub player_id: u32,
    pub quantity: i32,
}

impl From<GiveArrowsToPlayerArgs> for super::Reducer {
    fn from(args: GiveArrowsToPlayerArgs) -> Self {
        Self::GiveArrowsToPlayer {
            player_id: args.player_id,
            quantity: args.quantity,
        }
    }
}

impl __sdk::InModule for GiveArrowsToPlayerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `give_arrows_to_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait give_arrows_to_player {
    /// Request that the remote module invoke the reducer `give_arrows_to_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`give_arrows_to_player:give_arrows_to_player_then`] to run a callback after the reducer completes.
    fn give_arrows_to_player(&self, player_id: u32, quantity: i32) -> __sdk::Result<()> {
        self.give_arrows_to_player_then(player_id, quantity, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `give_arrows_to_player` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn give_arrows_to_player_then(
        &self,
        player_id: u32,
        quantity: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl give_arrows_to_player for super::RemoteReducers {
    fn give_arrows_to_player_then(
        &self,
        player_id: u32,
        quantity: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GiveArrowsToPlayerArgs {
                player_id,
                quantity,
            },
            callback,
        )
    }
}
