// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct HealPlayerArgs {
    pub player_id: u32,
    pub heal_amount: f32,
}

impl From<HealPlayerArgs> for super::Reducer {
    fn from(args: HealPlayerArgs) -> Self {
        Self::HealPlayer {
            player_id: args.player_id,
            heal_amount: args.heal_amount,
        }
    }
}

impl __sdk::InModule for HealPlayerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `heal_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait heal_player {
    /// Request that the remote module invoke the reducer `heal_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`heal_player:heal_player_then`] to run a callback after the reducer completes.
    fn heal_player(&self, player_id: u32, heal_amount: f32) -> __sdk::Result<()> {
        self.heal_player_then(player_id, heal_amount, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `heal_player` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn heal_player_then(
        &self,
        player_id: u32,
        heal_amount: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl heal_player for super::RemoteReducers {
    fn heal_player_then(
        &self,
        player_id: u32,
        heal_amount: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            HealPlayerArgs {
                player_id,
                heal_amount,
            },
            callback,
        )
    }
}
