// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InitMapTransitionsArgs {}

impl From<InitMapTransitionsArgs> for super::Reducer {
    fn from(args: InitMapTransitionsArgs) -> Self {
        Self::InitMapTransitions
    }
}

impl __sdk::InModule for InitMapTransitionsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `init_map_transitions`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait init_map_transitions {
    /// Request that the remote module invoke the reducer `init_map_transitions` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`init_map_transitions:init_map_transitions_then`] to run a callback after the reducer completes.
    fn init_map_transitions(&self) -> __sdk::Result<()> {
        self.init_map_transitions_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `init_map_transitions` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn init_map_transitions_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl init_map_transitions for super::RemoteReducers {
    fn init_map_transitions_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(InitMapTransitionsArgs {}, callback)
    }
}
