// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InteractableObject {
    pub id: u32,
    pub object_type: String,
    pub position_x: f32,
    pub position_y: f32,
    pub map_id: String,
    pub health: i32,
    pub max_health: i32,
    pub resource_count: i32,
    pub is_destroyed: bool,
    pub respawn_timer: f32,
}

impl __sdk::InModule for InteractableObject {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InteractableObject`.
///
/// Provides typed access to columns for query building.
pub struct InteractableObjectCols {
    pub id: __sdk::__query_builder::Col<InteractableObject, u32>,
    pub object_type: __sdk::__query_builder::Col<InteractableObject, String>,
    pub position_x: __sdk::__query_builder::Col<InteractableObject, f32>,
    pub position_y: __sdk::__query_builder::Col<InteractableObject, f32>,
    pub map_id: __sdk::__query_builder::Col<InteractableObject, String>,
    pub health: __sdk::__query_builder::Col<InteractableObject, i32>,
    pub max_health: __sdk::__query_builder::Col<InteractableObject, i32>,
    pub resource_count: __sdk::__query_builder::Col<InteractableObject, i32>,
    pub is_destroyed: __sdk::__query_builder::Col<InteractableObject, bool>,
    pub respawn_timer: __sdk::__query_builder::Col<InteractableObject, f32>,
}

impl __sdk::__query_builder::HasCols for InteractableObject {
    type Cols = InteractableObjectCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InteractableObjectCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            object_type: __sdk::__query_builder::Col::new(table_name, "object_type"),
            position_x: __sdk::__query_builder::Col::new(table_name, "position_x"),
            position_y: __sdk::__query_builder::Col::new(table_name, "position_y"),
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
            max_health: __sdk::__query_builder::Col::new(table_name, "max_health"),
            resource_count: __sdk::__query_builder::Col::new(table_name, "resource_count"),
            is_destroyed: __sdk::__query_builder::Col::new(table_name, "is_destroyed"),
            respawn_timer: __sdk::__query_builder::Col::new(table_name, "respawn_timer"),
        }
    }
}

/// Indexed column accessor struct for the table `InteractableObject`.
///
/// Provides typed access to indexed columns for query building.
pub struct InteractableObjectIxCols {
    pub id: __sdk::__query_builder::IxCol<InteractableObject, u32>,
}

impl __sdk::__query_builder::HasIxCols for InteractableObject {
    type IxCols = InteractableObjectIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InteractableObjectIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InteractableObject {}
