// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::interactable_object_type::InteractableObject;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `interactable_object`.
///
/// Obtain a handle from the [`InteractableObjectTableAccess::interactable_object`] method on [`super::RemoteTables`],
/// like `ctx.db.interactable_object()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.interactable_object().on_insert(...)`.
pub struct InteractableObjectTableHandle<'ctx> {
    imp: __sdk::TableHandle<InteractableObject>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `interactable_object`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InteractableObjectTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InteractableObjectTableHandle`], which mediates access to the table `interactable_object`.
    fn interactable_object(&self) -> InteractableObjectTableHandle<'_>;
}

impl InteractableObjectTableAccess for super::RemoteTables {
    fn interactable_object(&self) -> InteractableObjectTableHandle<'_> {
        InteractableObjectTableHandle {
            imp: self
                .imp
                .get_table::<InteractableObject>("interactable_object"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InteractableObjectInsertCallbackId(__sdk::CallbackId);
pub struct InteractableObjectDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InteractableObjectTableHandle<'ctx> {
    type Row = InteractableObject;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InteractableObject> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InteractableObjectInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InteractableObjectInsertCallbackId {
        InteractableObjectInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InteractableObjectInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InteractableObjectDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InteractableObjectDeleteCallbackId {
        InteractableObjectDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InteractableObjectDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct InteractableObjectUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InteractableObjectTableHandle<'ctx> {
    type UpdateCallbackId = InteractableObjectUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InteractableObjectUpdateCallbackId {
        InteractableObjectUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InteractableObjectUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `interactable_object`,
/// which allows point queries on the field of the same name
/// via the [`InteractableObjectIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.interactable_object().id().find(...)`.
pub struct InteractableObjectIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InteractableObject, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InteractableObjectTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `interactable_object`.
    pub fn id(&self) -> InteractableObjectIdUnique<'ctx> {
        InteractableObjectIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InteractableObjectIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<InteractableObject> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InteractableObject>("interactable_object");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InteractableObject>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InteractableObject>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InteractableObject`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait interactable_objectQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InteractableObject`.
    fn interactable_object(&self) -> __sdk::__query_builder::Table<InteractableObject>;
}

impl interactable_objectQueryTableAccess for __sdk::QueryTableAccessor {
    fn interactable_object(&self) -> __sdk::__query_builder::Table<InteractableObject> {
        __sdk::__query_builder::Table::new("interactable_object")
    }
}
