// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::inventory_item_type::InventoryItem;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `inventory_item`.
///
/// Obtain a handle from the [`InventoryItemTableAccess::inventory_item`] method on [`super::RemoteTables`],
/// like `ctx.db.inventory_item()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inventory_item().on_insert(...)`.
pub struct InventoryItemTableHandle<'ctx> {
    imp: __sdk::TableHandle<InventoryItem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `inventory_item`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InventoryItemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InventoryItemTableHandle`], which mediates access to the table `inventory_item`.
    fn inventory_item(&self) -> InventoryItemTableHandle<'_>;
}

impl InventoryItemTableAccess for super::RemoteTables {
    fn inventory_item(&self) -> InventoryItemTableHandle<'_> {
        InventoryItemTableHandle {
            imp: self.imp.get_table::<InventoryItem>("inventory_item"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InventoryItemInsertCallbackId(__sdk::CallbackId);
pub struct InventoryItemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InventoryItemTableHandle<'ctx> {
    type Row = InventoryItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InventoryItem> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InventoryItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InventoryItemInsertCallbackId {
        InventoryItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InventoryItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InventoryItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InventoryItemDeleteCallbackId {
        InventoryItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InventoryItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct InventoryItemUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InventoryItemTableHandle<'ctx> {
    type UpdateCallbackId = InventoryItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InventoryItemUpdateCallbackId {
        InventoryItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InventoryItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `inventory_item`,
/// which allows point queries on the field of the same name
/// via the [`InventoryItemIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inventory_item().id().find(...)`.
pub struct InventoryItemIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InventoryItem, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InventoryItemTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `inventory_item`.
    pub fn id(&self) -> InventoryItemIdUnique<'ctx> {
        InventoryItemIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InventoryItemIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<InventoryItem> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InventoryItem>("inventory_item");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InventoryItem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InventoryItem>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InventoryItem`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait inventory_itemQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InventoryItem`.
    fn inventory_item(&self) -> __sdk::__query_builder::Table<InventoryItem>;
}

impl inventory_itemQueryTableAccess for __sdk::QueryTableAccessor {
    fn inventory_item(&self) -> __sdk::__query_builder::Table<InventoryItem> {
        __sdk::__query_builder::Table::new("inventory_item")
    }
}
