// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InventoryItem {
    pub id: u32,
    pub player_id: u32,
    pub item_id: String,
    pub quantity: i32,
    pub is_equipped: bool,
    pub slot_type: String,
}

impl __sdk::InModule for InventoryItem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InventoryItem`.
///
/// Provides typed access to columns for query building.
pub struct InventoryItemCols {
    pub id: __sdk::__query_builder::Col<InventoryItem, u32>,
    pub player_id: __sdk::__query_builder::Col<InventoryItem, u32>,
    pub item_id: __sdk::__query_builder::Col<InventoryItem, String>,
    pub quantity: __sdk::__query_builder::Col<InventoryItem, i32>,
    pub is_equipped: __sdk::__query_builder::Col<InventoryItem, bool>,
    pub slot_type: __sdk::__query_builder::Col<InventoryItem, String>,
}

impl __sdk::__query_builder::HasCols for InventoryItem {
    type Cols = InventoryItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InventoryItemCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            item_id: __sdk::__query_builder::Col::new(table_name, "item_id"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            is_equipped: __sdk::__query_builder::Col::new(table_name, "is_equipped"),
            slot_type: __sdk::__query_builder::Col::new(table_name, "slot_type"),
        }
    }
}

/// Indexed column accessor struct for the table `InventoryItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct InventoryItemIxCols {
    pub id: __sdk::__query_builder::IxCol<InventoryItem, u32>,
}

impl __sdk::__query_builder::HasIxCols for InventoryItem {
    type IxCols = InventoryItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InventoryItemIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InventoryItem {}
