// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::map_transition_type::MapTransition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `map_transition`.
///
/// Obtain a handle from the [`MapTransitionTableAccess::map_transition`] method on [`super::RemoteTables`],
/// like `ctx.db.map_transition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_transition().on_insert(...)`.
pub struct MapTransitionTableHandle<'ctx> {
    imp: __sdk::TableHandle<MapTransition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `map_transition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MapTransitionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MapTransitionTableHandle`], which mediates access to the table `map_transition`.
    fn map_transition(&self) -> MapTransitionTableHandle<'_>;
}

impl MapTransitionTableAccess for super::RemoteTables {
    fn map_transition(&self) -> MapTransitionTableHandle<'_> {
        MapTransitionTableHandle {
            imp: self.imp.get_table::<MapTransition>("map_transition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MapTransitionInsertCallbackId(__sdk::CallbackId);
pub struct MapTransitionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MapTransitionTableHandle<'ctx> {
    type Row = MapTransition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MapTransition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MapTransitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapTransitionInsertCallbackId {
        MapTransitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MapTransitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MapTransitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapTransitionDeleteCallbackId {
        MapTransitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MapTransitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MapTransitionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MapTransitionTableHandle<'ctx> {
    type UpdateCallbackId = MapTransitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MapTransitionUpdateCallbackId {
        MapTransitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MapTransitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `map_transition`,
/// which allows point queries on the field of the same name
/// via the [`MapTransitionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_transition().id().find(...)`.
pub struct MapTransitionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MapTransition, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MapTransitionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `map_transition`.
    pub fn id(&self) -> MapTransitionIdUnique<'ctx> {
        MapTransitionIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MapTransitionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<MapTransition> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MapTransition>("map_transition");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MapTransition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MapTransition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MapTransition`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait map_transitionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MapTransition`.
    fn map_transition(&self) -> __sdk::__query_builder::Table<MapTransition>;
}

impl map_transitionQueryTableAccess for __sdk::QueryTableAccessor {
    fn map_transition(&self) -> __sdk::__query_builder::Table<MapTransition> {
        __sdk::__query_builder::Table::new("map_transition")
    }
}
