// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::map_template_type::MapTemplate;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `map_template`.
///
/// Obtain a handle from the [`MapTemplateTableAccess::map_template`] method on [`super::RemoteTables`],
/// like `ctx.db.map_template()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_template().on_insert(...)`.
pub struct MapTemplateTableHandle<'ctx> {
    imp: __sdk::TableHandle<MapTemplate>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `map_template`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MapTemplateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MapTemplateTableHandle`], which mediates access to the table `map_template`.
    fn map_template(&self) -> MapTemplateTableHandle<'_>;
}

impl MapTemplateTableAccess for super::RemoteTables {
    fn map_template(&self) -> MapTemplateTableHandle<'_> {
        MapTemplateTableHandle {
            imp: self.imp.get_table::<MapTemplate>("map_template"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MapTemplateInsertCallbackId(__sdk::CallbackId);
pub struct MapTemplateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MapTemplateTableHandle<'ctx> {
    type Row = MapTemplate;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MapTemplate> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MapTemplateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapTemplateInsertCallbackId {
        MapTemplateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MapTemplateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MapTemplateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapTemplateDeleteCallbackId {
        MapTemplateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MapTemplateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MapTemplateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MapTemplateTableHandle<'ctx> {
    type UpdateCallbackId = MapTemplateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MapTemplateUpdateCallbackId {
        MapTemplateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MapTemplateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `name` unique index on the table `map_template`,
/// which allows point queries on the field of the same name
/// via the [`MapTemplateNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_template().name().find(...)`.
pub struct MapTemplateNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MapTemplate, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MapTemplateTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `map_template`.
    pub fn name(&self) -> MapTemplateNameUnique<'ctx> {
        MapTemplateNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MapTemplateNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<MapTemplate> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MapTemplate>("map_template");
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MapTemplate>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MapTemplate>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MapTemplate`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait map_templateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MapTemplate`.
    fn map_template(&self) -> __sdk::__query_builder::Table<MapTemplate>;
}

impl map_templateQueryTableAccess for __sdk::QueryTableAccessor {
    fn map_template(&self) -> __sdk::__query_builder::Table<MapTemplate> {
        __sdk::__query_builder::Table::new("map_template")
    }
}
