// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MapInstance {
    pub id: u32,
    pub key_id: String,
    pub state: String,
    pub player_count: u32,
    pub template_name: String,
}

impl __sdk::InModule for MapInstance {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MapInstance`.
///
/// Provides typed access to columns for query building.
pub struct MapInstanceCols {
    pub id: __sdk::__query_builder::Col<MapInstance, u32>,
    pub key_id: __sdk::__query_builder::Col<MapInstance, String>,
    pub state: __sdk::__query_builder::Col<MapInstance, String>,
    pub player_count: __sdk::__query_builder::Col<MapInstance, u32>,
    pub template_name: __sdk::__query_builder::Col<MapInstance, String>,
}

impl __sdk::__query_builder::HasCols for MapInstance {
    type Cols = MapInstanceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MapInstanceCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            key_id: __sdk::__query_builder::Col::new(table_name, "key_id"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            player_count: __sdk::__query_builder::Col::new(table_name, "player_count"),
            template_name: __sdk::__query_builder::Col::new(table_name, "template_name"),
        }
    }
}

/// Indexed column accessor struct for the table `MapInstance`.
///
/// Provides typed access to indexed columns for query building.
pub struct MapInstanceIxCols {
    pub id: __sdk::__query_builder::IxCol<MapInstance, u32>,
    pub key_id: __sdk::__query_builder::IxCol<MapInstance, String>,
}

impl __sdk::__query_builder::HasIxCols for MapInstance {
    type IxCols = MapInstanceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MapInstanceIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            key_id: __sdk::__query_builder::IxCol::new(table_name, "key_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MapInstance {}
