// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::map_instance_type::MapInstance;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `map_instance`.
///
/// Obtain a handle from the [`MapInstanceTableAccess::map_instance`] method on [`super::RemoteTables`],
/// like `ctx.db.map_instance()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_instance().on_insert(...)`.
pub struct MapInstanceTableHandle<'ctx> {
    imp: __sdk::TableHandle<MapInstance>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `map_instance`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MapInstanceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MapInstanceTableHandle`], which mediates access to the table `map_instance`.
    fn map_instance(&self) -> MapInstanceTableHandle<'_>;
}

impl MapInstanceTableAccess for super::RemoteTables {
    fn map_instance(&self) -> MapInstanceTableHandle<'_> {
        MapInstanceTableHandle {
            imp: self.imp.get_table::<MapInstance>("map_instance"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MapInstanceInsertCallbackId(__sdk::CallbackId);
pub struct MapInstanceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MapInstanceTableHandle<'ctx> {
    type Row = MapInstance;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MapInstance> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MapInstanceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapInstanceInsertCallbackId {
        MapInstanceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MapInstanceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MapInstanceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapInstanceDeleteCallbackId {
        MapInstanceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MapInstanceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MapInstanceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MapInstanceTableHandle<'ctx> {
    type UpdateCallbackId = MapInstanceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MapInstanceUpdateCallbackId {
        MapInstanceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MapInstanceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `map_instance`,
/// which allows point queries on the field of the same name
/// via the [`MapInstanceIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_instance().id().find(...)`.
pub struct MapInstanceIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MapInstance, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MapInstanceTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `map_instance`.
    pub fn id(&self) -> MapInstanceIdUnique<'ctx> {
        MapInstanceIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MapInstanceIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<MapInstance> {
        self.imp.find(col_val)
    }
}

/// Access to the `key_id` unique index on the table `map_instance`,
/// which allows point queries on the field of the same name
/// via the [`MapInstanceKeyIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_instance().key_id().find(...)`.
pub struct MapInstanceKeyIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MapInstance, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MapInstanceTableHandle<'ctx> {
    /// Get a handle on the `key_id` unique index on the table `map_instance`.
    pub fn key_id(&self) -> MapInstanceKeyIdUnique<'ctx> {
        MapInstanceKeyIdUnique {
            imp: self.imp.get_unique_constraint::<String>("key_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MapInstanceKeyIdUnique<'ctx> {
    /// Find the subscribed row whose `key_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<MapInstance> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MapInstance>("map_instance");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("key_id", |row| &row.key_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MapInstance>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MapInstance>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MapInstance`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait map_instanceQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MapInstance`.
    fn map_instance(&self) -> __sdk::__query_builder::Table<MapInstance>;
}

impl map_instanceQueryTableAccess for __sdk::QueryTableAccessor {
    fn map_instance(&self) -> __sdk::__query_builder::Table<MapInstance> {
        __sdk::__query_builder::Table::new("map_instance")
    }
}
