// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MapTransition {
    pub id: u32,
    pub map_id: String,
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
    pub dest_map_id: String,
    pub dest_x: f32,
    pub dest_y: f32,
}

impl __sdk::InModule for MapTransition {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MapTransition`.
///
/// Provides typed access to columns for query building.
pub struct MapTransitionCols {
    pub id: __sdk::__query_builder::Col<MapTransition, u32>,
    pub map_id: __sdk::__query_builder::Col<MapTransition, String>,
    pub x: __sdk::__query_builder::Col<MapTransition, f32>,
    pub y: __sdk::__query_builder::Col<MapTransition, f32>,
    pub width: __sdk::__query_builder::Col<MapTransition, f32>,
    pub height: __sdk::__query_builder::Col<MapTransition, f32>,
    pub dest_map_id: __sdk::__query_builder::Col<MapTransition, String>,
    pub dest_x: __sdk::__query_builder::Col<MapTransition, f32>,
    pub dest_y: __sdk::__query_builder::Col<MapTransition, f32>,
}

impl __sdk::__query_builder::HasCols for MapTransition {
    type Cols = MapTransitionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MapTransitionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            width: __sdk::__query_builder::Col::new(table_name, "width"),
            height: __sdk::__query_builder::Col::new(table_name, "height"),
            dest_map_id: __sdk::__query_builder::Col::new(table_name, "dest_map_id"),
            dest_x: __sdk::__query_builder::Col::new(table_name, "dest_x"),
            dest_y: __sdk::__query_builder::Col::new(table_name, "dest_y"),
        }
    }
}

/// Indexed column accessor struct for the table `MapTransition`.
///
/// Provides typed access to indexed columns for query building.
pub struct MapTransitionIxCols {
    pub id: __sdk::__query_builder::IxCol<MapTransition, u32>,
}

impl __sdk::__query_builder::HasIxCols for MapTransition {
    type IxCols = MapTransitionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MapTransitionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MapTransition {}
