// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MapTemplate {
    pub name: String,
    pub width: u32,
    pub height: u32,
    pub tile_data: Vec<u32>,
    pub spawn_x: f32,
    pub spawn_y: f32,
}

impl __sdk::InModule for MapTemplate {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MapTemplate`.
///
/// Provides typed access to columns for query building.
pub struct MapTemplateCols {
    pub name: __sdk::__query_builder::Col<MapTemplate, String>,
    pub width: __sdk::__query_builder::Col<MapTemplate, u32>,
    pub height: __sdk::__query_builder::Col<MapTemplate, u32>,
    pub tile_data: __sdk::__query_builder::Col<MapTemplate, Vec<u32>>,
    pub spawn_x: __sdk::__query_builder::Col<MapTemplate, f32>,
    pub spawn_y: __sdk::__query_builder::Col<MapTemplate, f32>,
}

impl __sdk::__query_builder::HasCols for MapTemplate {
    type Cols = MapTemplateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MapTemplateCols {
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            width: __sdk::__query_builder::Col::new(table_name, "width"),
            height: __sdk::__query_builder::Col::new(table_name, "height"),
            tile_data: __sdk::__query_builder::Col::new(table_name, "tile_data"),
            spawn_x: __sdk::__query_builder::Col::new(table_name, "spawn_x"),
            spawn_y: __sdk::__query_builder::Col::new(table_name, "spawn_y"),
        }
    }
}

/// Indexed column accessor struct for the table `MapTemplate`.
///
/// Provides typed access to indexed columns for query building.
pub struct MapTemplateIxCols {
    pub name: __sdk::__query_builder::IxCol<MapTemplate, String>,
}

impl __sdk::__query_builder::HasIxCols for MapTemplate {
    type IxCols = MapTemplateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MapTemplateIxCols {
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MapTemplate {}
