// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.5 (commit d60138999206c06c776829072f46b5d1c1101f7e).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod add_item_to_inventory_reducer;
pub mod apply_damage_to_player_reducer;
pub mod combat_event_table;
pub mod combat_event_type;
pub mod container_item_table;
pub mod container_item_type;
pub mod container_table;
pub mod container_type;
pub mod create_container_reducer;
pub mod create_interactable_object_reducer;
pub mod create_projectile_reducer;
pub mod deposit_item_reducer;
pub mod enemy_attack_player_reducer;
pub mod enemy_table;
pub mod enemy_transition_map_reducer;
pub mod enemy_type;
pub mod equip_item_reducer;
pub mod execute_attack_reducer;
pub mod execute_contextual_action_reducer;
pub mod force_player_position_reducer;
pub mod get_map_data_reducer;
pub mod get_player_info_reducer;
pub mod get_player_position_reducer;
pub mod get_projectiles_in_map_reducer;
pub mod get_resource_by_id_reducer;
pub mod get_resource_by_key_reducer;
pub mod give_arrows_to_player_reducer;
pub mod heal_player_reducer;
pub mod health_check_reducer;
pub mod init_map_transitions_reducer;
pub mod interactable_object_table;
pub mod interactable_object_type;
pub mod inventory_item_table;
pub mod inventory_item_type;
pub mod list_resources_by_type_reducer;
pub mod map_instance_table;
pub mod map_instance_type;
pub mod map_template_table;
pub mod map_template_type;
pub mod map_transition_table;
pub mod map_transition_type;
pub mod pickup_item_reducer;
pub mod player_equipment_table;
pub mod player_equipment_type;
pub mod player_table;
pub mod player_type;
pub mod process_hit_reducer;
pub mod projectile_table;
pub mod projectile_type;
pub mod register_player_reducer;
pub mod register_resource_reducer;
pub mod remove_enemy_reducer;
pub mod remove_resource_reducer;
pub mod replace_all_templates_reducer;
pub mod resource_id_mapping_table;
pub mod resource_id_mapping_type;
pub mod resource_registry_table;
pub mod resource_registry_type;
pub mod revive_player_reducer;
pub mod set_player_max_health_reducer;
pub mod spawn_enemy_reducer;
pub mod spawn_player_at_map_reducer;
pub mod spawn_test_enemy_reducer;
pub mod sync_resource_registry_reducer;
pub mod test_message_reducer;
pub mod unequip_item_reducer;
pub mod update_enemy_ai_reducer;
pub mod update_player_position_reducer;
pub mod update_projectiles_reducer;
pub mod update_resource_reducer;
pub mod use_health_consumable_reducer;
pub mod withdraw_item_reducer;
pub mod world_mutation_table;
pub mod world_mutation_type;

pub use add_item_to_inventory_reducer::add_item_to_inventory;
pub use apply_damage_to_player_reducer::apply_damage_to_player;
pub use combat_event_table::*;
pub use combat_event_type::CombatEvent;
pub use container_item_table::*;
pub use container_item_type::ContainerItem;
pub use container_table::*;
pub use container_type::Container;
pub use create_container_reducer::create_container;
pub use create_interactable_object_reducer::create_interactable_object;
pub use create_projectile_reducer::create_projectile;
pub use deposit_item_reducer::deposit_item;
pub use enemy_attack_player_reducer::enemy_attack_player;
pub use enemy_table::*;
pub use enemy_transition_map_reducer::enemy_transition_map;
pub use enemy_type::Enemy;
pub use equip_item_reducer::equip_item;
pub use execute_attack_reducer::execute_attack;
pub use execute_contextual_action_reducer::execute_contextual_action;
pub use force_player_position_reducer::force_player_position;
pub use get_map_data_reducer::get_map_data;
pub use get_player_info_reducer::get_player_info;
pub use get_player_position_reducer::get_player_position;
pub use get_projectiles_in_map_reducer::get_projectiles_in_map;
pub use get_resource_by_id_reducer::get_resource_by_id;
pub use get_resource_by_key_reducer::get_resource_by_key;
pub use give_arrows_to_player_reducer::give_arrows_to_player;
pub use heal_player_reducer::heal_player;
pub use health_check_reducer::health_check;
pub use init_map_transitions_reducer::init_map_transitions;
pub use interactable_object_table::*;
pub use interactable_object_type::InteractableObject;
pub use inventory_item_table::*;
pub use inventory_item_type::InventoryItem;
pub use list_resources_by_type_reducer::list_resources_by_type;
pub use map_instance_table::*;
pub use map_instance_type::MapInstance;
pub use map_template_table::*;
pub use map_template_type::MapTemplate;
pub use map_transition_table::*;
pub use map_transition_type::MapTransition;
pub use pickup_item_reducer::pickup_item;
pub use player_equipment_table::*;
pub use player_equipment_type::PlayerEquipment;
pub use player_table::*;
pub use player_type::Player;
pub use process_hit_reducer::process_hit;
pub use projectile_table::*;
pub use projectile_type::Projectile;
pub use register_player_reducer::register_player;
pub use register_resource_reducer::register_resource;
pub use remove_enemy_reducer::remove_enemy;
pub use remove_resource_reducer::remove_resource;
pub use replace_all_templates_reducer::replace_all_templates;
pub use resource_id_mapping_table::*;
pub use resource_id_mapping_type::ResourceIdMapping;
pub use resource_registry_table::*;
pub use resource_registry_type::ResourceRegistry;
pub use revive_player_reducer::revive_player;
pub use set_player_max_health_reducer::set_player_max_health;
pub use spawn_enemy_reducer::spawn_enemy;
pub use spawn_player_at_map_reducer::spawn_player_at_map;
pub use spawn_test_enemy_reducer::spawn_test_enemy;
pub use sync_resource_registry_reducer::sync_resource_registry;
pub use test_message_reducer::test_message;
pub use unequip_item_reducer::unequip_item;
pub use update_enemy_ai_reducer::update_enemy_ai;
pub use update_player_position_reducer::update_player_position;
pub use update_projectiles_reducer::update_projectiles;
pub use update_resource_reducer::update_resource;
pub use use_health_consumable_reducer::use_health_consumable;
pub use withdraw_item_reducer::withdraw_item;
pub use world_mutation_table::*;
pub use world_mutation_type::WorldMutation;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AddItemToInventory {
        player_id: u32,
        item_id: String,
        quantity: i32,
    },
    ApplyDamageToPlayer {
        player_id: u32,
        damage: f32,
        attacker_id: u32,
    },
    CreateContainer {
        position_x: f32,
        position_y: f32,
        map_id: String,
        capacity: u32,
        label: String,
    },
    CreateInteractableObject {
        object_type: String,
        position_x: f32,
        position_y: f32,
        map_id: String,
    },
    CreateProjectile {
        player_id: u32,
        origin_x: f32,
        origin_y: f32,
        direction_x: f32,
        direction_y: f32,
    },
    DepositItem {
        container_id: u32,
        item_id: String,
        quantity: i32,
    },
    EnemyAttackPlayer {
        enemy_id: u32,
        player_id: u32,
        damage: f32,
    },
    EnemyTransitionMap {
        enemy_id: u32,
        destination_map_id: String,
        spawn_x: f32,
        spawn_y: f32,
    },
    EquipItem {
        player_id: u32,
        item_id: String,
    },
    ExecuteAttack {
        player_id: u32,
        weapon_type: String,
        direction_x: f32,
        direction_y: f32,
    },
    ExecuteContextualAction {
        player_id: u32,
        object_id: u32,
        action_type: String,
    },
    ForcePlayerPosition {
        player_id: u32,
        x: f32,
        y: f32,
    },
    GetMapData {
        map_id: String,
    },
    GetPlayerInfo,
    GetPlayerPosition {
        player_id: u32,
    },
    GetProjectilesInMap {
        map_id: String,
    },
    GetResourceById {
        resource_id: u32,
    },
    GetResourceByKey {
        key_id: String,
    },
    GiveArrowsToPlayer {
        player_id: u32,
        quantity: i32,
    },
    HealPlayer {
        player_id: u32,
        heal_amount: f32,
    },
    HealthCheck,
    InitMapTransitions,
    ListResourcesByType {
        resource_type: String,
    },
    PickupItem {
        player_id: u32,
        item_id: String,
        quantity: i32,
        position_x: f32,
        position_y: f32,
    },
    ProcessHit {
        attacker_id: u32,
        target_id: u32,
        damage: f32,
    },
    RegisterPlayer {
        username_display: String,
    },
    RegisterResource {
        key_id: String,
        resource_type: String,
        data: String,
    },
    RemoveEnemy {
        enemy_id: u32,
    },
    RemoveResource {
        key_id: String,
    },
    ReplaceAllTemplates {
        new_templates: Vec<MapTemplate>,
    },
    RevivePlayer {
        player_id: u32,
        reviver_id: u32,
    },
    SetPlayerMaxHealth {
        player_id: u32,
        max_health: f32,
    },
    SpawnEnemy {
        enemy_id: u32,
        position_x: f32,
        position_y: f32,
        map_id: String,
        enemy_type: String,
    },
    SpawnPlayerAtMap {
        player_id: u32,
        map_id: String,
    },
    SpawnTestEnemy {
        position_x: f32,
        position_y: f32,
        map_id: String,
    },
    SyncResourceRegistry,
    TestMessage {
        message: String,
    },
    UnequipItem {
        player_id: u32,
        item_id: String,
    },
    UpdateEnemyAi {
        enemy_id: u32,
        new_state: String,
        position_x: f32,
        position_y: f32,
        velocity_x: f32,
        velocity_y: f32,
        target_player_id: Option<u32>,
        last_known_player_x: f32,
        last_known_player_y: f32,
    },
    UpdatePlayerPosition {
        player_id: u32,
        new_x: f32,
        new_y: f32,
        velocity_x: f32,
        velocity_y: f32,
        input_sequence: u32,
    },
    UpdateProjectiles {
        delta_time: f32,
    },
    UpdateResource {
        key_id: String,
        new_data: String,
    },
    UseHealthConsumable {
        player_id: u32,
        item_id: String,
    },
    WithdrawItem {
        container_id: u32,
        item_id: String,
        quantity: i32,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AddItemToInventory { .. } => "add_item_to_inventory",
            Reducer::ApplyDamageToPlayer { .. } => "apply_damage_to_player",
            Reducer::CreateContainer { .. } => "create_container",
            Reducer::CreateInteractableObject { .. } => "create_interactable_object",
            Reducer::CreateProjectile { .. } => "create_projectile",
            Reducer::DepositItem { .. } => "deposit_item",
            Reducer::EnemyAttackPlayer { .. } => "enemy_attack_player",
            Reducer::EnemyTransitionMap { .. } => "enemy_transition_map",
            Reducer::EquipItem { .. } => "equip_item",
            Reducer::ExecuteAttack { .. } => "execute_attack",
            Reducer::ExecuteContextualAction { .. } => "execute_contextual_action",
            Reducer::ForcePlayerPosition { .. } => "force_player_position",
            Reducer::GetMapData { .. } => "get_map_data",
            Reducer::GetPlayerInfo => "get_player_info",
            Reducer::GetPlayerPosition { .. } => "get_player_position",
            Reducer::GetProjectilesInMap { .. } => "get_projectiles_in_map",
            Reducer::GetResourceById { .. } => "get_resource_by_id",
            Reducer::GetResourceByKey { .. } => "get_resource_by_key",
            Reducer::GiveArrowsToPlayer { .. } => "give_arrows_to_player",
            Reducer::HealPlayer { .. } => "heal_player",
            Reducer::HealthCheck => "health_check",
            Reducer::InitMapTransitions => "init_map_transitions",
            Reducer::ListResourcesByType { .. } => "list_resources_by_type",
            Reducer::PickupItem { .. } => "pickup_item",
            Reducer::ProcessHit { .. } => "process_hit",
            Reducer::RegisterPlayer { .. } => "register_player",
            Reducer::RegisterResource { .. } => "register_resource",
            Reducer::RemoveEnemy { .. } => "remove_enemy",
            Reducer::RemoveResource { .. } => "remove_resource",
            Reducer::ReplaceAllTemplates { .. } => "replace_all_templates",
            Reducer::RevivePlayer { .. } => "revive_player",
            Reducer::SetPlayerMaxHealth { .. } => "set_player_max_health",
            Reducer::SpawnEnemy { .. } => "spawn_enemy",
            Reducer::SpawnPlayerAtMap { .. } => "spawn_player_at_map",
            Reducer::SpawnTestEnemy { .. } => "spawn_test_enemy",
            Reducer::SyncResourceRegistry => "sync_resource_registry",
            Reducer::TestMessage { .. } => "test_message",
            Reducer::UnequipItem { .. } => "unequip_item",
            Reducer::UpdateEnemyAi { .. } => "update_enemy_ai",
            Reducer::UpdatePlayerPosition { .. } => "update_player_position",
            Reducer::UpdateProjectiles { .. } => "update_projectiles",
            Reducer::UpdateResource { .. } => "update_resource",
            Reducer::UseHealthConsumable { .. } => "use_health_consumable",
            Reducer::WithdrawItem { .. } => "withdraw_item",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AddItemToInventory {
                player_id,
                item_id,
                quantity,
            } => __sats::bsatn::to_vec(&add_item_to_inventory_reducer::AddItemToInventoryArgs {
                player_id: player_id.clone(),
                item_id: item_id.clone(),
                quantity: quantity.clone(),
            }),
            Reducer::ApplyDamageToPlayer {
                player_id,
                damage,
                attacker_id,
            } => __sats::bsatn::to_vec(&apply_damage_to_player_reducer::ApplyDamageToPlayerArgs {
                player_id: player_id.clone(),
                damage: damage.clone(),
                attacker_id: attacker_id.clone(),
            }),
            Reducer::CreateContainer {
                position_x,
                position_y,
                map_id,
                capacity,
                label,
            } => __sats::bsatn::to_vec(&create_container_reducer::CreateContainerArgs {
                position_x: position_x.clone(),
                position_y: position_y.clone(),
                map_id: map_id.clone(),
                capacity: capacity.clone(),
                label: label.clone(),
            }),
            Reducer::CreateInteractableObject {
                object_type,
                position_x,
                position_y,
                map_id,
            } => __sats::bsatn::to_vec(
                &create_interactable_object_reducer::CreateInteractableObjectArgs {
                    object_type: object_type.clone(),
                    position_x: position_x.clone(),
                    position_y: position_y.clone(),
                    map_id: map_id.clone(),
                },
            ),
            Reducer::CreateProjectile {
                player_id,
                origin_x,
                origin_y,
                direction_x,
                direction_y,
            } => __sats::bsatn::to_vec(&create_projectile_reducer::CreateProjectileArgs {
                player_id: player_id.clone(),
                origin_x: origin_x.clone(),
                origin_y: origin_y.clone(),
                direction_x: direction_x.clone(),
                direction_y: direction_y.clone(),
            }),
            Reducer::DepositItem {
                container_id,
                item_id,
                quantity,
            } => __sats::bsatn::to_vec(&deposit_item_reducer::DepositItemArgs {
                container_id: container_id.clone(),
                item_id: item_id.clone(),
                quantity: quantity.clone(),
            }),
            Reducer::EnemyAttackPlayer {
                enemy_id,
                player_id,
                damage,
            } => __sats::bsatn::to_vec(&enemy_attack_player_reducer::EnemyAttackPlayerArgs {
                enemy_id: enemy_id.clone(),
                player_id: player_id.clone(),
                damage: damage.clone(),
            }),
            Reducer::EnemyTransitionMap {
                enemy_id,
                destination_map_id,
                spawn_x,
                spawn_y,
            } => __sats::bsatn::to_vec(&enemy_transition_map_reducer::EnemyTransitionMapArgs {
                enemy_id: enemy_id.clone(),
                destination_map_id: destination_map_id.clone(),
                spawn_x: spawn_x.clone(),
                spawn_y: spawn_y.clone(),
            }),
            Reducer::EquipItem { player_id, item_id } => {
                __sats::bsatn::to_vec(&equip_item_reducer::EquipItemArgs {
                    player_id: player_id.clone(),
                    item_id: item_id.clone(),
                })
            }
            Reducer::ExecuteAttack {
                player_id,
                weapon_type,
                direction_x,
                direction_y,
            } => __sats::bsatn::to_vec(&execute_attack_reducer::ExecuteAttackArgs {
                player_id: player_id.clone(),
                weapon_type: weapon_type.clone(),
                direction_x: direction_x.clone(),
                direction_y: direction_y.clone(),
            }),
            Reducer::ExecuteContextualAction {
                player_id,
                object_id,
                action_type,
            } => __sats::bsatn::to_vec(
                &execute_contextual_action_reducer::ExecuteContextualActionArgs {
                    player_id: player_id.clone(),
                    object_id: object_id.clone(),
                    action_type: action_type.clone(),
                },
            ),
            Reducer::ForcePlayerPosition { player_id, x, y } => {
                __sats::bsatn::to_vec(&force_player_position_reducer::ForcePlayerPositionArgs {
                    player_id: player_id.clone(),
                    x: x.clone(),
                    y: y.clone(),
                })
            }
            Reducer::GetMapData { map_id } => {
                __sats::bsatn::to_vec(&get_map_data_reducer::GetMapDataArgs {
                    map_id: map_id.clone(),
                })
            }
            Reducer::GetPlayerInfo => {
                __sats::bsatn::to_vec(&get_player_info_reducer::GetPlayerInfoArgs {})
            }
            Reducer::GetPlayerPosition { player_id } => {
                __sats::bsatn::to_vec(&get_player_position_reducer::GetPlayerPositionArgs {
                    player_id: player_id.clone(),
                })
            }
            Reducer::GetProjectilesInMap { map_id } => {
                __sats::bsatn::to_vec(&get_projectiles_in_map_reducer::GetProjectilesInMapArgs {
                    map_id: map_id.clone(),
                })
            }
            Reducer::GetResourceById { resource_id } => {
                __sats::bsatn::to_vec(&get_resource_by_id_reducer::GetResourceByIdArgs {
                    resource_id: resource_id.clone(),
                })
            }
            Reducer::GetResourceByKey { key_id } => {
                __sats::bsatn::to_vec(&get_resource_by_key_reducer::GetResourceByKeyArgs {
                    key_id: key_id.clone(),
                })
            }
            Reducer::GiveArrowsToPlayer {
                player_id,
                quantity,
            } => __sats::bsatn::to_vec(&give_arrows_to_player_reducer::GiveArrowsToPlayerArgs {
                player_id: player_id.clone(),
                quantity: quantity.clone(),
            }),
            Reducer::HealPlayer {
                player_id,
                heal_amount,
            } => __sats::bsatn::to_vec(&heal_player_reducer::HealPlayerArgs {
                player_id: player_id.clone(),
                heal_amount: heal_amount.clone(),
            }),
            Reducer::HealthCheck => {
                __sats::bsatn::to_vec(&health_check_reducer::HealthCheckArgs {})
            }
            Reducer::InitMapTransitions => {
                __sats::bsatn::to_vec(&init_map_transitions_reducer::InitMapTransitionsArgs {})
            }
            Reducer::ListResourcesByType { resource_type } => {
                __sats::bsatn::to_vec(&list_resources_by_type_reducer::ListResourcesByTypeArgs {
                    resource_type: resource_type.clone(),
                })
            }
            Reducer::PickupItem {
                player_id,
                item_id,
                quantity,
                position_x,
                position_y,
            } => __sats::bsatn::to_vec(&pickup_item_reducer::PickupItemArgs {
                player_id: player_id.clone(),
                item_id: item_id.clone(),
                quantity: quantity.clone(),
                position_x: position_x.clone(),
                position_y: position_y.clone(),
            }),
            Reducer::ProcessHit {
                attacker_id,
                target_id,
                damage,
            } => __sats::bsatn::to_vec(&process_hit_reducer::ProcessHitArgs {
                attacker_id: attacker_id.clone(),
                target_id: target_id.clone(),
                damage: damage.clone(),
            }),
            Reducer::RegisterPlayer { username_display } => {
                __sats::bsatn::to_vec(&register_player_reducer::RegisterPlayerArgs {
                    username_display: username_display.clone(),
                })
            }
            Reducer::RegisterResource {
                key_id,
                resource_type,
                data,
            } => __sats::bsatn::to_vec(&register_resource_reducer::RegisterResourceArgs {
                key_id: key_id.clone(),
                resource_type: resource_type.clone(),
                data: data.clone(),
            }),
            Reducer::RemoveEnemy { enemy_id } => {
                __sats::bsatn::to_vec(&remove_enemy_reducer::RemoveEnemyArgs {
                    enemy_id: enemy_id.clone(),
                })
            }
            Reducer::RemoveResource { key_id } => {
                __sats::bsatn::to_vec(&remove_resource_reducer::RemoveResourceArgs {
                    key_id: key_id.clone(),
                })
            }
            Reducer::ReplaceAllTemplates { new_templates } => {
                __sats::bsatn::to_vec(&replace_all_templates_reducer::ReplaceAllTemplatesArgs {
                    new_templates: new_templates.clone(),
                })
            }
            Reducer::RevivePlayer {
                player_id,
                reviver_id,
            } => __sats::bsatn::to_vec(&revive_player_reducer::RevivePlayerArgs {
                player_id: player_id.clone(),
                reviver_id: reviver_id.clone(),
            }),
            Reducer::SetPlayerMaxHealth {
                player_id,
                max_health,
            } => __sats::bsatn::to_vec(&set_player_max_health_reducer::SetPlayerMaxHealthArgs {
                player_id: player_id.clone(),
                max_health: max_health.clone(),
            }),
            Reducer::SpawnEnemy {
                enemy_id,
                position_x,
                position_y,
                map_id,
                enemy_type,
            } => __sats::bsatn::to_vec(&spawn_enemy_reducer::SpawnEnemyArgs {
                enemy_id: enemy_id.clone(),
                position_x: position_x.clone(),
                position_y: position_y.clone(),
                map_id: map_id.clone(),
                enemy_type: enemy_type.clone(),
            }),
            Reducer::SpawnPlayerAtMap { player_id, map_id } => {
                __sats::bsatn::to_vec(&spawn_player_at_map_reducer::SpawnPlayerAtMapArgs {
                    player_id: player_id.clone(),
                    map_id: map_id.clone(),
                })
            }
            Reducer::SpawnTestEnemy {
                position_x,
                position_y,
                map_id,
            } => __sats::bsatn::to_vec(&spawn_test_enemy_reducer::SpawnTestEnemyArgs {
                position_x: position_x.clone(),
                position_y: position_y.clone(),
                map_id: map_id.clone(),
            }),
            Reducer::SyncResourceRegistry => {
                __sats::bsatn::to_vec(&sync_resource_registry_reducer::SyncResourceRegistryArgs {})
            }
            Reducer::TestMessage { message } => {
                __sats::bsatn::to_vec(&test_message_reducer::TestMessageArgs {
                    message: message.clone(),
                })
            }
            Reducer::UnequipItem { player_id, item_id } => {
                __sats::bsatn::to_vec(&unequip_item_reducer::UnequipItemArgs {
                    player_id: player_id.clone(),
                    item_id: item_id.clone(),
                })
            }
            Reducer::UpdateEnemyAi {
                enemy_id,
                new_state,
                position_x,
                position_y,
                velocity_x,
                velocity_y,
                target_player_id,
                last_known_player_x,
                last_known_player_y,
            } => __sats::bsatn::to_vec(&update_enemy_ai_reducer::UpdateEnemyAiArgs {
                enemy_id: enemy_id.clone(),
                new_state: new_state.clone(),
                position_x: position_x.clone(),
                position_y: position_y.clone(),
                velocity_x: velocity_x.clone(),
                velocity_y: velocity_y.clone(),
                target_player_id: target_player_id.clone(),
                last_known_player_x: last_known_player_x.clone(),
                last_known_player_y: last_known_player_y.clone(),
            }),
            Reducer::UpdatePlayerPosition {
                player_id,
                new_x,
                new_y,
                velocity_x,
                velocity_y,
                input_sequence,
            } => __sats::bsatn::to_vec(&update_player_position_reducer::UpdatePlayerPositionArgs {
                player_id: player_id.clone(),
                new_x: new_x.clone(),
                new_y: new_y.clone(),
                velocity_x: velocity_x.clone(),
                velocity_y: velocity_y.clone(),
                input_sequence: input_sequence.clone(),
            }),
            Reducer::UpdateProjectiles { delta_time } => {
                __sats::bsatn::to_vec(&update_projectiles_reducer::UpdateProjectilesArgs {
                    delta_time: delta_time.clone(),
                })
            }
            Reducer::UpdateResource { key_id, new_data } => {
                __sats::bsatn::to_vec(&update_resource_reducer::UpdateResourceArgs {
                    key_id: key_id.clone(),
                    new_data: new_data.clone(),
                })
            }
            Reducer::UseHealthConsumable { player_id, item_id } => {
                __sats::bsatn::to_vec(&use_health_consumable_reducer::UseHealthConsumableArgs {
                    player_id: player_id.clone(),
                    item_id: item_id.clone(),
                })
            }
            Reducer::WithdrawItem {
                container_id,
                item_id,
                quantity,
            } => __sats::bsatn::to_vec(&withdraw_item_reducer::WithdrawItemArgs {
                container_id: container_id.clone(),
                item_id: item_id.clone(),
                quantity: quantity.clone(),
            }),
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    combat_event: __sdk::TableUpdate<CombatEvent>,
    container: __sdk::TableUpdate<Container>,
    container_item: __sdk::TableUpdate<ContainerItem>,
    enemy: __sdk::TableUpdate<Enemy>,
    interactable_object: __sdk::TableUpdate<InteractableObject>,
    inventory_item: __sdk::TableUpdate<InventoryItem>,
    map_instance: __sdk::TableUpdate<MapInstance>,
    map_template: __sdk::TableUpdate<MapTemplate>,
    map_transition: __sdk::TableUpdate<MapTransition>,
    player: __sdk::TableUpdate<Player>,
    player_equipment: __sdk::TableUpdate<PlayerEquipment>,
    projectile: __sdk::TableUpdate<Projectile>,
    resource_id_mapping: __sdk::TableUpdate<ResourceIdMapping>,
    resource_registry: __sdk::TableUpdate<ResourceRegistry>,
    world_mutation: __sdk::TableUpdate<WorldMutation>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "combat_event" => db_update
                    .combat_event
                    .append(combat_event_table::parse_table_update(table_update)?),
                "container" => db_update
                    .container
                    .append(container_table::parse_table_update(table_update)?),
                "container_item" => db_update
                    .container_item
                    .append(container_item_table::parse_table_update(table_update)?),
                "enemy" => db_update
                    .enemy
                    .append(enemy_table::parse_table_update(table_update)?),
                "interactable_object" => db_update
                    .interactable_object
                    .append(interactable_object_table::parse_table_update(table_update)?),
                "inventory_item" => db_update
                    .inventory_item
                    .append(inventory_item_table::parse_table_update(table_update)?),
                "map_instance" => db_update
                    .map_instance
                    .append(map_instance_table::parse_table_update(table_update)?),
                "map_template" => db_update
                    .map_template
                    .append(map_template_table::parse_table_update(table_update)?),
                "map_transition" => db_update
                    .map_transition
                    .append(map_transition_table::parse_table_update(table_update)?),
                "player" => db_update
                    .player
                    .append(player_table::parse_table_update(table_update)?),
                "player_equipment" => db_update
                    .player_equipment
                    .append(player_equipment_table::parse_table_update(table_update)?),
                "projectile" => db_update
                    .projectile
                    .append(projectile_table::parse_table_update(table_update)?),
                "resource_id_mapping" => db_update
                    .resource_id_mapping
                    .append(resource_id_mapping_table::parse_table_update(table_update)?),
                "resource_registry" => db_update
                    .resource_registry
                    .append(resource_registry_table::parse_table_update(table_update)?),
                "world_mutation" => db_update
                    .world_mutation
                    .append(world_mutation_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.combat_event = cache
            .apply_diff_to_table::<CombatEvent>("combat_event", &self.combat_event)
            .with_updates_by_pk(|row| &row.id);
        diff.container = cache
            .apply_diff_to_table::<Container>("container", &self.container)
            .with_updates_by_pk(|row| &row.id);
        diff.container_item = cache
            .apply_diff_to_table::<ContainerItem>("container_item", &self.container_item)
            .with_updates_by_pk(|row| &row.id);
        diff.enemy = cache
            .apply_diff_to_table::<Enemy>("enemy", &self.enemy)
            .with_updates_by_pk(|row| &row.id);
        diff.interactable_object = cache
            .apply_diff_to_table::<InteractableObject>(
                "interactable_object",
                &self.interactable_object,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.inventory_item = cache
            .apply_diff_to_table::<InventoryItem>("inventory_item", &self.inventory_item)
            .with_updates_by_pk(|row| &row.id);
        diff.map_instance = cache
            .apply_diff_to_table::<MapInstance>("map_instance", &self.map_instance)
            .with_updates_by_pk(|row| &row.id);
        diff.map_template = cache
            .apply_diff_to_table::<MapTemplate>("map_template", &self.map_template)
            .with_updates_by_pk(|row| &row.name);
        diff.map_transition = cache
            .apply_diff_to_table::<MapTransition>("map_transition", &self.map_transition)
            .with_updates_by_pk(|row| &row.id);
        diff.player = cache
            .apply_diff_to_table::<Player>("player", &self.player)
            .with_updates_by_pk(|row| &row.id);
        diff.player_equipment = cache
            .apply_diff_to_table::<PlayerEquipment>("player_equipment", &self.player_equipment)
            .with_updates_by_pk(|row| &row.player_id);
        diff.projectile = cache
            .apply_diff_to_table::<Projectile>("projectile", &self.projectile)
            .with_updates_by_pk(|row| &row.id);
        diff.resource_id_mapping = cache
            .apply_diff_to_table::<ResourceIdMapping>(
                "resource_id_mapping",
                &self.resource_id_mapping,
            )
            .with_updates_by_pk(|row| &row.key_id);
        diff.resource_registry = cache
            .apply_diff_to_table::<ResourceRegistry>("resource_registry", &self.resource_registry)
            .with_updates_by_pk(|row| &row.id);
        diff.world_mutation = cache
            .apply_diff_to_table::<WorldMutation>("world_mutation", &self.world_mutation)
            .with_updates_by_pk(|row| &row.id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "combat_event" => db_update
                    .combat_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "container" => db_update
                    .container
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "container_item" => db_update
                    .container_item
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "enemy" => db_update
                    .enemy
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "interactable_object" => db_update
                    .interactable_object
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "inventory_item" => db_update
                    .inventory_item
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "map_instance" => db_update
                    .map_instance
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "map_template" => db_update
                    .map_template
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "map_transition" => db_update
                    .map_transition
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_equipment" => db_update
                    .player_equipment
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "projectile" => db_update
                    .projectile
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "resource_id_mapping" => db_update
                    .resource_id_mapping
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "resource_registry" => db_update
                    .resource_registry
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "world_mutation" => db_update
                    .world_mutation
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "combat_event" => db_update
                    .combat_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "container" => db_update
                    .container
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "container_item" => db_update
                    .container_item
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "enemy" => db_update
                    .enemy
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "interactable_object" => db_update
                    .interactable_object
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "inventory_item" => db_update
                    .inventory_item
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "map_instance" => db_update
                    .map_instance
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "map_template" => db_update
                    .map_template
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "map_transition" => db_update
                    .map_transition
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_equipment" => db_update
                    .player_equipment
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "projectile" => db_update
                    .projectile
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "resource_id_mapping" => db_update
                    .resource_id_mapping
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "resource_registry" => db_update
                    .resource_registry
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "world_mutation" => db_update
                    .world_mutation
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    combat_event: __sdk::TableAppliedDiff<'r, CombatEvent>,
    container: __sdk::TableAppliedDiff<'r, Container>,
    container_item: __sdk::TableAppliedDiff<'r, ContainerItem>,
    enemy: __sdk::TableAppliedDiff<'r, Enemy>,
    interactable_object: __sdk::TableAppliedDiff<'r, InteractableObject>,
    inventory_item: __sdk::TableAppliedDiff<'r, InventoryItem>,
    map_instance: __sdk::TableAppliedDiff<'r, MapInstance>,
    map_template: __sdk::TableAppliedDiff<'r, MapTemplate>,
    map_transition: __sdk::TableAppliedDiff<'r, MapTransition>,
    player: __sdk::TableAppliedDiff<'r, Player>,
    player_equipment: __sdk::TableAppliedDiff<'r, PlayerEquipment>,
    projectile: __sdk::TableAppliedDiff<'r, Projectile>,
    resource_id_mapping: __sdk::TableAppliedDiff<'r, ResourceIdMapping>,
    resource_registry: __sdk::TableAppliedDiff<'r, ResourceRegistry>,
    world_mutation: __sdk::TableAppliedDiff<'r, WorldMutation>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<CombatEvent>(
            "combat_event",
            &self.combat_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Container>("container", &self.container, event);
        callbacks.invoke_table_row_callbacks::<ContainerItem>(
            "container_item",
            &self.container_item,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Enemy>("enemy", &self.enemy, event);
        callbacks.invoke_table_row_callbacks::<InteractableObject>(
            "interactable_object",
            &self.interactable_object,
            event,
        );
        callbacks.invoke_table_row_callbacks::<InventoryItem>(
            "inventory_item",
            &self.inventory_item,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MapInstance>(
            "map_instance",
            &self.map_instance,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MapTemplate>(
            "map_template",
            &self.map_template,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MapTransition>(
            "map_transition",
            &self.map_transition,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Player>("player", &self.player, event);
        callbacks.invoke_table_row_callbacks::<PlayerEquipment>(
            "player_equipment",
            &self.player_equipment,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Projectile>("projectile", &self.projectile, event);
        callbacks.invoke_table_row_callbacks::<ResourceIdMapping>(
            "resource_id_mapping",
            &self.resource_id_mapping,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ResourceRegistry>(
            "resource_registry",
            &self.resource_registry,
            event,
        );
        callbacks.invoke_table_row_callbacks::<WorldMutation>(
            "world_mutation",
            &self.world_mutation,
            event,
        );
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        combat_event_table::register_table(client_cache);
        container_table::register_table(client_cache);
        container_item_table::register_table(client_cache);
        enemy_table::register_table(client_cache);
        interactable_object_table::register_table(client_cache);
        inventory_item_table::register_table(client_cache);
        map_instance_table::register_table(client_cache);
        map_template_table::register_table(client_cache);
        map_transition_table::register_table(client_cache);
        player_table::register_table(client_cache);
        player_equipment_table::register_table(client_cache);
        projectile_table::register_table(client_cache);
        resource_id_mapping_table::register_table(client_cache);
        resource_registry_table::register_table(client_cache);
        world_mutation_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "combat_event",
        "container",
        "container_item",
        "enemy",
        "interactable_object",
        "inventory_item",
        "map_instance",
        "map_template",
        "map_transition",
        "player",
        "player_equipment",
        "projectile",
        "resource_id_mapping",
        "resource_registry",
        "world_mutation",
    ];
}
