// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PickupItemArgs {
    pub player_id: u32,
    pub item_id: String,
    pub quantity: i32,
    pub position_x: f32,
    pub position_y: f32,
}

impl From<PickupItemArgs> for super::Reducer {
    fn from(args: PickupItemArgs) -> Self {
        Self::PickupItem {
            player_id: args.player_id,
            item_id: args.item_id,
            quantity: args.quantity,
            position_x: args.position_x,
            position_y: args.position_y,
        }
    }
}

impl __sdk::InModule for PickupItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `pickup_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait pickup_item {
    /// Request that the remote module invoke the reducer `pickup_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`pickup_item:pickup_item_then`] to run a callback after the reducer completes.
    fn pickup_item(
        &self,
        player_id: u32,
        item_id: String,
        quantity: i32,
        position_x: f32,
        position_y: f32,
    ) -> __sdk::Result<()> {
        self.pickup_item_then(
            player_id,
            item_id,
            quantity,
            position_x,
            position_y,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `pickup_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn pickup_item_then(
        &self,
        player_id: u32,
        item_id: String,
        quantity: i32,
        position_x: f32,
        position_y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl pickup_item for super::RemoteReducers {
    fn pickup_item_then(
        &self,
        player_id: u32,
        item_id: String,
        quantity: i32,
        position_x: f32,
        position_y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PickupItemArgs {
                player_id,
                item_id,
                quantity,
                position_x,
                position_y,
            },
            callback,
        )
    }
}
