// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerEquipment {
    pub player_id: u32,
    pub main_hand_weapon: String,
    pub off_hand_tool: String,
    pub armor: String,
    pub accessory: String,
}

impl __sdk::InModule for PlayerEquipment {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerEquipment`.
///
/// Provides typed access to columns for query building.
pub struct PlayerEquipmentCols {
    pub player_id: __sdk::__query_builder::Col<PlayerEquipment, u32>,
    pub main_hand_weapon: __sdk::__query_builder::Col<PlayerEquipment, String>,
    pub off_hand_tool: __sdk::__query_builder::Col<PlayerEquipment, String>,
    pub armor: __sdk::__query_builder::Col<PlayerEquipment, String>,
    pub accessory: __sdk::__query_builder::Col<PlayerEquipment, String>,
}

impl __sdk::__query_builder::HasCols for PlayerEquipment {
    type Cols = PlayerEquipmentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerEquipmentCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            main_hand_weapon: __sdk::__query_builder::Col::new(table_name, "main_hand_weapon"),
            off_hand_tool: __sdk::__query_builder::Col::new(table_name, "off_hand_tool"),
            armor: __sdk::__query_builder::Col::new(table_name, "armor"),
            accessory: __sdk::__query_builder::Col::new(table_name, "accessory"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerEquipment`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerEquipmentIxCols {
    pub player_id: __sdk::__query_builder::IxCol<PlayerEquipment, u32>,
}

impl __sdk::__query_builder::HasIxCols for PlayerEquipment {
    type IxCols = PlayerEquipmentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerEquipmentIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerEquipment {}
