// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Player {
    pub id: u32,
    pub username_canonical: String,
    pub username_display: String,
    pub identity: __sdk::Identity,
    pub position_x: f32,
    pub position_y: f32,
    pub velocity_x: f32,
    pub velocity_y: f32,
    pub current_map_id: String,
    pub health: f32,
    pub max_health: f32,
    pub is_downed: bool,
    pub last_input_sequence: u32,
    pub last_transition_time: __sdk::Timestamp,
}

impl __sdk::InModule for Player {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Player`.
///
/// Provides typed access to columns for query building.
pub struct PlayerCols {
    pub id: __sdk::__query_builder::Col<Player, u32>,
    pub username_canonical: __sdk::__query_builder::Col<Player, String>,
    pub username_display: __sdk::__query_builder::Col<Player, String>,
    pub identity: __sdk::__query_builder::Col<Player, __sdk::Identity>,
    pub position_x: __sdk::__query_builder::Col<Player, f32>,
    pub position_y: __sdk::__query_builder::Col<Player, f32>,
    pub velocity_x: __sdk::__query_builder::Col<Player, f32>,
    pub velocity_y: __sdk::__query_builder::Col<Player, f32>,
    pub current_map_id: __sdk::__query_builder::Col<Player, String>,
    pub health: __sdk::__query_builder::Col<Player, f32>,
    pub max_health: __sdk::__query_builder::Col<Player, f32>,
    pub is_downed: __sdk::__query_builder::Col<Player, bool>,
    pub last_input_sequence: __sdk::__query_builder::Col<Player, u32>,
    pub last_transition_time: __sdk::__query_builder::Col<Player, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Player {
    type Cols = PlayerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            username_canonical: __sdk::__query_builder::Col::new(table_name, "username_canonical"),
            username_display: __sdk::__query_builder::Col::new(table_name, "username_display"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            position_x: __sdk::__query_builder::Col::new(table_name, "position_x"),
            position_y: __sdk::__query_builder::Col::new(table_name, "position_y"),
            velocity_x: __sdk::__query_builder::Col::new(table_name, "velocity_x"),
            velocity_y: __sdk::__query_builder::Col::new(table_name, "velocity_y"),
            current_map_id: __sdk::__query_builder::Col::new(table_name, "current_map_id"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
            max_health: __sdk::__query_builder::Col::new(table_name, "max_health"),
            is_downed: __sdk::__query_builder::Col::new(table_name, "is_downed"),
            last_input_sequence: __sdk::__query_builder::Col::new(
                table_name,
                "last_input_sequence",
            ),
            last_transition_time: __sdk::__query_builder::Col::new(
                table_name,
                "last_transition_time",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `Player`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerIxCols {
    pub id: __sdk::__query_builder::IxCol<Player, u32>,
    pub identity: __sdk::__query_builder::IxCol<Player, __sdk::Identity>,
    pub username_canonical: __sdk::__query_builder::IxCol<Player, String>,
}

impl __sdk::__query_builder::HasIxCols for Player {
    type IxCols = PlayerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
            username_canonical: __sdk::__query_builder::IxCol::new(
                table_name,
                "username_canonical",
            ),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Player {}
