// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Projectile {
    pub id: u32,
    pub owner_id: u32,
    pub position_x: f32,
    pub position_y: f32,
    pub velocity_x: f32,
    pub velocity_y: f32,
    pub damage: f32,
    pub time_to_live: f32,
    pub projectile_type: String,
    pub map_id: String,
    pub is_active: bool,
}

impl __sdk::InModule for Projectile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Projectile`.
///
/// Provides typed access to columns for query building.
pub struct ProjectileCols {
    pub id: __sdk::__query_builder::Col<Projectile, u32>,
    pub owner_id: __sdk::__query_builder::Col<Projectile, u32>,
    pub position_x: __sdk::__query_builder::Col<Projectile, f32>,
    pub position_y: __sdk::__query_builder::Col<Projectile, f32>,
    pub velocity_x: __sdk::__query_builder::Col<Projectile, f32>,
    pub velocity_y: __sdk::__query_builder::Col<Projectile, f32>,
    pub damage: __sdk::__query_builder::Col<Projectile, f32>,
    pub time_to_live: __sdk::__query_builder::Col<Projectile, f32>,
    pub projectile_type: __sdk::__query_builder::Col<Projectile, String>,
    pub map_id: __sdk::__query_builder::Col<Projectile, String>,
    pub is_active: __sdk::__query_builder::Col<Projectile, bool>,
}

impl __sdk::__query_builder::HasCols for Projectile {
    type Cols = ProjectileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProjectileCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner_id: __sdk::__query_builder::Col::new(table_name, "owner_id"),
            position_x: __sdk::__query_builder::Col::new(table_name, "position_x"),
            position_y: __sdk::__query_builder::Col::new(table_name, "position_y"),
            velocity_x: __sdk::__query_builder::Col::new(table_name, "velocity_x"),
            velocity_y: __sdk::__query_builder::Col::new(table_name, "velocity_y"),
            damage: __sdk::__query_builder::Col::new(table_name, "damage"),
            time_to_live: __sdk::__query_builder::Col::new(table_name, "time_to_live"),
            projectile_type: __sdk::__query_builder::Col::new(table_name, "projectile_type"),
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
        }
    }
}

/// Indexed column accessor struct for the table `Projectile`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProjectileIxCols {
    pub id: __sdk::__query_builder::IxCol<Projectile, u32>,
}

impl __sdk::__query_builder::HasIxCols for Projectile {
    type IxCols = ProjectileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProjectileIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Projectile {}
