// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterResourceArgs {
    pub key_id: String,
    pub resource_type: String,
    pub data: String,
}

impl From<RegisterResourceArgs> for super::Reducer {
    fn from(args: RegisterResourceArgs) -> Self {
        Self::RegisterResource {
            key_id: args.key_id,
            resource_type: args.resource_type,
            data: args.data,
        }
    }
}

impl __sdk::InModule for RegisterResourceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_resource`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_resource {
    /// Request that the remote module invoke the reducer `register_resource` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_resource:register_resource_then`] to run a callback after the reducer completes.
    fn register_resource(
        &self,
        key_id: String,
        resource_type: String,
        data: String,
    ) -> __sdk::Result<()> {
        self.register_resource_then(key_id, resource_type, data, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `register_resource` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_resource_then(
        &self,
        key_id: String,
        resource_type: String,
        data: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_resource for super::RemoteReducers {
    fn register_resource_then(
        &self,
        key_id: String,
        resource_type: String,
        data: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterResourceArgs {
                key_id,
                resource_type,
                data,
            },
            callback,
        )
    }
}
