// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::map_template_type::MapTemplate;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReplaceAllTemplatesArgs {
    pub new_templates: Vec<MapTemplate>,
}

impl From<ReplaceAllTemplatesArgs> for super::Reducer {
    fn from(args: ReplaceAllTemplatesArgs) -> Self {
        Self::ReplaceAllTemplates {
            new_templates: args.new_templates,
        }
    }
}

impl __sdk::InModule for ReplaceAllTemplatesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `replace_all_templates`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait replace_all_templates {
    /// Request that the remote module invoke the reducer `replace_all_templates` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`replace_all_templates:replace_all_templates_then`] to run a callback after the reducer completes.
    fn replace_all_templates(&self, new_templates: Vec<MapTemplate>) -> __sdk::Result<()> {
        self.replace_all_templates_then(new_templates, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `replace_all_templates` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn replace_all_templates_then(
        &self,
        new_templates: Vec<MapTemplate>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl replace_all_templates for super::RemoteReducers {
    fn replace_all_templates_then(
        &self,
        new_templates: Vec<MapTemplate>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ReplaceAllTemplatesArgs { new_templates }, callback)
    }
}
