// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ResourceRegistry {
    pub id: u32,
    pub key_id: String,
    pub resource_type: String,
    pub data: String,
    pub hash_disambiguation: u32,
}

impl __sdk::InModule for ResourceRegistry {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ResourceRegistry`.
///
/// Provides typed access to columns for query building.
pub struct ResourceRegistryCols {
    pub id: __sdk::__query_builder::Col<ResourceRegistry, u32>,
    pub key_id: __sdk::__query_builder::Col<ResourceRegistry, String>,
    pub resource_type: __sdk::__query_builder::Col<ResourceRegistry, String>,
    pub data: __sdk::__query_builder::Col<ResourceRegistry, String>,
    pub hash_disambiguation: __sdk::__query_builder::Col<ResourceRegistry, u32>,
}

impl __sdk::__query_builder::HasCols for ResourceRegistry {
    type Cols = ResourceRegistryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ResourceRegistryCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            key_id: __sdk::__query_builder::Col::new(table_name, "key_id"),
            resource_type: __sdk::__query_builder::Col::new(table_name, "resource_type"),
            data: __sdk::__query_builder::Col::new(table_name, "data"),
            hash_disambiguation: __sdk::__query_builder::Col::new(
                table_name,
                "hash_disambiguation",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `ResourceRegistry`.
///
/// Provides typed access to indexed columns for query building.
pub struct ResourceRegistryIxCols {
    pub id: __sdk::__query_builder::IxCol<ResourceRegistry, u32>,
}

impl __sdk::__query_builder::HasIxCols for ResourceRegistry {
    type IxCols = ResourceRegistryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ResourceRegistryIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ResourceRegistry {}
