// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::resource_id_mapping_type::ResourceIdMapping;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `resource_id_mapping`.
///
/// Obtain a handle from the [`ResourceIdMappingTableAccess::resource_id_mapping`] method on [`super::RemoteTables`],
/// like `ctx.db.resource_id_mapping()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resource_id_mapping().on_insert(...)`.
pub struct ResourceIdMappingTableHandle<'ctx> {
    imp: __sdk::TableHandle<ResourceIdMapping>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `resource_id_mapping`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ResourceIdMappingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ResourceIdMappingTableHandle`], which mediates access to the table `resource_id_mapping`.
    fn resource_id_mapping(&self) -> ResourceIdMappingTableHandle<'_>;
}

impl ResourceIdMappingTableAccess for super::RemoteTables {
    fn resource_id_mapping(&self) -> ResourceIdMappingTableHandle<'_> {
        ResourceIdMappingTableHandle {
            imp: self
                .imp
                .get_table::<ResourceIdMapping>("resource_id_mapping"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ResourceIdMappingInsertCallbackId(__sdk::CallbackId);
pub struct ResourceIdMappingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ResourceIdMappingTableHandle<'ctx> {
    type Row = ResourceIdMapping;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ResourceIdMapping> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ResourceIdMappingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceIdMappingInsertCallbackId {
        ResourceIdMappingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ResourceIdMappingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ResourceIdMappingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceIdMappingDeleteCallbackId {
        ResourceIdMappingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ResourceIdMappingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ResourceIdMappingUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ResourceIdMappingTableHandle<'ctx> {
    type UpdateCallbackId = ResourceIdMappingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ResourceIdMappingUpdateCallbackId {
        ResourceIdMappingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ResourceIdMappingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key_id` unique index on the table `resource_id_mapping`,
/// which allows point queries on the field of the same name
/// via the [`ResourceIdMappingKeyIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resource_id_mapping().key_id().find(...)`.
pub struct ResourceIdMappingKeyIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ResourceIdMapping, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ResourceIdMappingTableHandle<'ctx> {
    /// Get a handle on the `key_id` unique index on the table `resource_id_mapping`.
    pub fn key_id(&self) -> ResourceIdMappingKeyIdUnique<'ctx> {
        ResourceIdMappingKeyIdUnique {
            imp: self.imp.get_unique_constraint::<String>("key_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ResourceIdMappingKeyIdUnique<'ctx> {
    /// Find the subscribed row whose `key_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<ResourceIdMapping> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ResourceIdMapping>("resource_id_mapping");
    _table.add_unique_constraint::<String>("key_id", |row| &row.key_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ResourceIdMapping>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ResourceIdMapping>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ResourceIdMapping`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait resource_id_mappingQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ResourceIdMapping`.
    fn resource_id_mapping(&self) -> __sdk::__query_builder::Table<ResourceIdMapping>;
}

impl resource_id_mappingQueryTableAccess for __sdk::QueryTableAccessor {
    fn resource_id_mapping(&self) -> __sdk::__query_builder::Table<ResourceIdMapping> {
        __sdk::__query_builder::Table::new("resource_id_mapping")
    }
}
