// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ResourceIdMapping {
    pub key_id: String,
    pub resource_id: u32,
}

impl __sdk::InModule for ResourceIdMapping {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ResourceIdMapping`.
///
/// Provides typed access to columns for query building.
pub struct ResourceIdMappingCols {
    pub key_id: __sdk::__query_builder::Col<ResourceIdMapping, String>,
    pub resource_id: __sdk::__query_builder::Col<ResourceIdMapping, u32>,
}

impl __sdk::__query_builder::HasCols for ResourceIdMapping {
    type Cols = ResourceIdMappingCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ResourceIdMappingCols {
            key_id: __sdk::__query_builder::Col::new(table_name, "key_id"),
            resource_id: __sdk::__query_builder::Col::new(table_name, "resource_id"),
        }
    }
}

/// Indexed column accessor struct for the table `ResourceIdMapping`.
///
/// Provides typed access to indexed columns for query building.
pub struct ResourceIdMappingIxCols {
    pub key_id: __sdk::__query_builder::IxCol<ResourceIdMapping, String>,
}

impl __sdk::__query_builder::HasIxCols for ResourceIdMapping {
    type IxCols = ResourceIdMappingIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ResourceIdMappingIxCols {
            key_id: __sdk::__query_builder::IxCol::new(table_name, "key_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ResourceIdMapping {}
