// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::resource_registry_type::ResourceRegistry;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `resource_registry`.
///
/// Obtain a handle from the [`ResourceRegistryTableAccess::resource_registry`] method on [`super::RemoteTables`],
/// like `ctx.db.resource_registry()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resource_registry().on_insert(...)`.
pub struct ResourceRegistryTableHandle<'ctx> {
    imp: __sdk::TableHandle<ResourceRegistry>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `resource_registry`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ResourceRegistryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ResourceRegistryTableHandle`], which mediates access to the table `resource_registry`.
    fn resource_registry(&self) -> ResourceRegistryTableHandle<'_>;
}

impl ResourceRegistryTableAccess for super::RemoteTables {
    fn resource_registry(&self) -> ResourceRegistryTableHandle<'_> {
        ResourceRegistryTableHandle {
            imp: self.imp.get_table::<ResourceRegistry>("resource_registry"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ResourceRegistryInsertCallbackId(__sdk::CallbackId);
pub struct ResourceRegistryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ResourceRegistryTableHandle<'ctx> {
    type Row = ResourceRegistry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ResourceRegistry> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ResourceRegistryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceRegistryInsertCallbackId {
        ResourceRegistryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ResourceRegistryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ResourceRegistryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceRegistryDeleteCallbackId {
        ResourceRegistryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ResourceRegistryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ResourceRegistryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ResourceRegistryTableHandle<'ctx> {
    type UpdateCallbackId = ResourceRegistryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ResourceRegistryUpdateCallbackId {
        ResourceRegistryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ResourceRegistryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `resource_registry`,
/// which allows point queries on the field of the same name
/// via the [`ResourceRegistryIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resource_registry().id().find(...)`.
pub struct ResourceRegistryIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ResourceRegistry, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ResourceRegistryTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `resource_registry`.
    pub fn id(&self) -> ResourceRegistryIdUnique<'ctx> {
        ResourceRegistryIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ResourceRegistryIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<ResourceRegistry> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ResourceRegistry>("resource_registry");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ResourceRegistry>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ResourceRegistry>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ResourceRegistry`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait resource_registryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ResourceRegistry`.
    fn resource_registry(&self) -> __sdk::__query_builder::Table<ResourceRegistry>;
}

impl resource_registryQueryTableAccess for __sdk::QueryTableAccessor {
    fn resource_registry(&self) -> __sdk::__query_builder::Table<ResourceRegistry> {
        __sdk::__query_builder::Table::new("resource_registry")
    }
}
