// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RevivePlayerArgs {
    pub player_id: u32,
    pub reviver_id: u32,
}

impl From<RevivePlayerArgs> for super::Reducer {
    fn from(args: RevivePlayerArgs) -> Self {
        Self::RevivePlayer {
            player_id: args.player_id,
            reviver_id: args.reviver_id,
        }
    }
}

impl __sdk::InModule for RevivePlayerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `revive_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait revive_player {
    /// Request that the remote module invoke the reducer `revive_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`revive_player:revive_player_then`] to run a callback after the reducer completes.
    fn revive_player(&self, player_id: u32, reviver_id: u32) -> __sdk::Result<()> {
        self.revive_player_then(player_id, reviver_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `revive_player` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn revive_player_then(
        &self,
        player_id: u32,
        reviver_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl revive_player for super::RemoteReducers {
    fn revive_player_then(
        &self,
        player_id: u32,
        reviver_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RevivePlayerArgs {
                player_id,
                reviver_id,
            },
            callback,
        )
    }
}
