// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetPlayerMaxHealthArgs {
    pub player_id: u32,
    pub max_health: f32,
}

impl From<SetPlayerMaxHealthArgs> for super::Reducer {
    fn from(args: SetPlayerMaxHealthArgs) -> Self {
        Self::SetPlayerMaxHealth {
            player_id: args.player_id,
            max_health: args.max_health,
        }
    }
}

impl __sdk::InModule for SetPlayerMaxHealthArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_player_max_health`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_player_max_health {
    /// Request that the remote module invoke the reducer `set_player_max_health` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_player_max_health:set_player_max_health_then`] to run a callback after the reducer completes.
    fn set_player_max_health(&self, player_id: u32, max_health: f32) -> __sdk::Result<()> {
        self.set_player_max_health_then(player_id, max_health, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_player_max_health` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_player_max_health_then(
        &self,
        player_id: u32,
        max_health: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_player_max_health for super::RemoteReducers {
    fn set_player_max_health_then(
        &self,
        player_id: u32,
        max_health: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetPlayerMaxHealthArgs {
                player_id,
                max_health,
            },
            callback,
        )
    }
}
