// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnTestEnemyArgs {
    pub position_x: f32,
    pub position_y: f32,
    pub map_id: String,
}

impl From<SpawnTestEnemyArgs> for super::Reducer {
    fn from(args: SpawnTestEnemyArgs) -> Self {
        Self::SpawnTestEnemy {
            position_x: args.position_x,
            position_y: args.position_y,
            map_id: args.map_id,
        }
    }
}

impl __sdk::InModule for SpawnTestEnemyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_test_enemy`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_test_enemy {
    /// Request that the remote module invoke the reducer `spawn_test_enemy` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`spawn_test_enemy:spawn_test_enemy_then`] to run a callback after the reducer completes.
    fn spawn_test_enemy(
        &self,
        position_x: f32,
        position_y: f32,
        map_id: String,
    ) -> __sdk::Result<()> {
        self.spawn_test_enemy_then(position_x, position_y, map_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `spawn_test_enemy` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn spawn_test_enemy_then(
        &self,
        position_x: f32,
        position_y: f32,
        map_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl spawn_test_enemy for super::RemoteReducers {
    fn spawn_test_enemy_then(
        &self,
        position_x: f32,
        position_y: f32,
        map_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SpawnTestEnemyArgs {
                position_x,
                position_y,
                map_id,
            },
            callback,
        )
    }
}
