// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnPlayerAtMapArgs {
    pub player_id: u32,
    pub map_id: String,
}

impl From<SpawnPlayerAtMapArgs> for super::Reducer {
    fn from(args: SpawnPlayerAtMapArgs) -> Self {
        Self::SpawnPlayerAtMap {
            player_id: args.player_id,
            map_id: args.map_id,
        }
    }
}

impl __sdk::InModule for SpawnPlayerAtMapArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_player_at_map`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_player_at_map {
    /// Request that the remote module invoke the reducer `spawn_player_at_map` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`spawn_player_at_map:spawn_player_at_map_then`] to run a callback after the reducer completes.
    fn spawn_player_at_map(&self, player_id: u32, map_id: String) -> __sdk::Result<()> {
        self.spawn_player_at_map_then(player_id, map_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `spawn_player_at_map` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn spawn_player_at_map_then(
        &self,
        player_id: u32,
        map_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl spawn_player_at_map for super::RemoteReducers {
    fn spawn_player_at_map_then(
        &self,
        player_id: u32,
        map_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SpawnPlayerAtMapArgs { player_id, map_id }, callback)
    }
}
