// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnEnemyArgs {
    pub enemy_id: u32,
    pub position_x: f32,
    pub position_y: f32,
    pub map_id: String,
    pub enemy_type: String,
}

impl From<SpawnEnemyArgs> for super::Reducer {
    fn from(args: SpawnEnemyArgs) -> Self {
        Self::SpawnEnemy {
            enemy_id: args.enemy_id,
            position_x: args.position_x,
            position_y: args.position_y,
            map_id: args.map_id,
            enemy_type: args.enemy_type,
        }
    }
}

impl __sdk::InModule for SpawnEnemyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_enemy`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_enemy {
    /// Request that the remote module invoke the reducer `spawn_enemy` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`spawn_enemy:spawn_enemy_then`] to run a callback after the reducer completes.
    fn spawn_enemy(
        &self,
        enemy_id: u32,
        position_x: f32,
        position_y: f32,
        map_id: String,
        enemy_type: String,
    ) -> __sdk::Result<()> {
        self.spawn_enemy_then(
            enemy_id,
            position_x,
            position_y,
            map_id,
            enemy_type,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `spawn_enemy` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn spawn_enemy_then(
        &self,
        enemy_id: u32,
        position_x: f32,
        position_y: f32,
        map_id: String,
        enemy_type: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl spawn_enemy for super::RemoteReducers {
    fn spawn_enemy_then(
        &self,
        enemy_id: u32,
        position_x: f32,
        position_y: f32,
        map_id: String,
        enemy_type: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SpawnEnemyArgs {
                enemy_id,
                position_x,
                position_y,
                map_id,
                enemy_type,
            },
            callback,
        )
    }
}
