// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdatePlayerPositionArgs {
    pub player_id: u32,
    pub new_x: f32,
    pub new_y: f32,
    pub velocity_x: f32,
    pub velocity_y: f32,
    pub input_sequence: u32,
}

impl From<UpdatePlayerPositionArgs> for super::Reducer {
    fn from(args: UpdatePlayerPositionArgs) -> Self {
        Self::UpdatePlayerPosition {
            player_id: args.player_id,
            new_x: args.new_x,
            new_y: args.new_y,
            velocity_x: args.velocity_x,
            velocity_y: args.velocity_y,
            input_sequence: args.input_sequence,
        }
    }
}

impl __sdk::InModule for UpdatePlayerPositionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_player_position`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_player_position {
    /// Request that the remote module invoke the reducer `update_player_position` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_player_position:update_player_position_then`] to run a callback after the reducer completes.
    fn update_player_position(
        &self,
        player_id: u32,
        new_x: f32,
        new_y: f32,
        velocity_x: f32,
        velocity_y: f32,
        input_sequence: u32,
    ) -> __sdk::Result<()> {
        self.update_player_position_then(
            player_id,
            new_x,
            new_y,
            velocity_x,
            velocity_y,
            input_sequence,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `update_player_position` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_player_position_then(
        &self,
        player_id: u32,
        new_x: f32,
        new_y: f32,
        velocity_x: f32,
        velocity_y: f32,
        input_sequence: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_player_position for super::RemoteReducers {
    fn update_player_position_then(
        &self,
        player_id: u32,
        new_x: f32,
        new_y: f32,
        velocity_x: f32,
        velocity_y: f32,
        input_sequence: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdatePlayerPositionArgs {
                player_id,
                new_x,
                new_y,
                velocity_x,
                velocity_y,
                input_sequence,
            },
            callback,
        )
    }
}
