// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateEnemyAiArgs {
    pub enemy_id: u32,
    pub new_state: String,
    pub position_x: f32,
    pub position_y: f32,
    pub velocity_x: f32,
    pub velocity_y: f32,
    pub target_player_id: Option<u32>,
    pub last_known_player_x: f32,
    pub last_known_player_y: f32,
}

impl From<UpdateEnemyAiArgs> for super::Reducer {
    fn from(args: UpdateEnemyAiArgs) -> Self {
        Self::UpdateEnemyAi {
            enemy_id: args.enemy_id,
            new_state: args.new_state,
            position_x: args.position_x,
            position_y: args.position_y,
            velocity_x: args.velocity_x,
            velocity_y: args.velocity_y,
            target_player_id: args.target_player_id,
            last_known_player_x: args.last_known_player_x,
            last_known_player_y: args.last_known_player_y,
        }
    }
}

impl __sdk::InModule for UpdateEnemyAiArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_enemy_ai`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_enemy_ai {
    /// Request that the remote module invoke the reducer `update_enemy_ai` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_enemy_ai:update_enemy_ai_then`] to run a callback after the reducer completes.
    fn update_enemy_ai(
        &self,
        enemy_id: u32,
        new_state: String,
        position_x: f32,
        position_y: f32,
        velocity_x: f32,
        velocity_y: f32,
        target_player_id: Option<u32>,
        last_known_player_x: f32,
        last_known_player_y: f32,
    ) -> __sdk::Result<()> {
        self.update_enemy_ai_then(
            enemy_id,
            new_state,
            position_x,
            position_y,
            velocity_x,
            velocity_y,
            target_player_id,
            last_known_player_x,
            last_known_player_y,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `update_enemy_ai` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_enemy_ai_then(
        &self,
        enemy_id: u32,
        new_state: String,
        position_x: f32,
        position_y: f32,
        velocity_x: f32,
        velocity_y: f32,
        target_player_id: Option<u32>,
        last_known_player_x: f32,
        last_known_player_y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_enemy_ai for super::RemoteReducers {
    fn update_enemy_ai_then(
        &self,
        enemy_id: u32,
        new_state: String,
        position_x: f32,
        position_y: f32,
        velocity_x: f32,
        velocity_y: f32,
        target_player_id: Option<u32>,
        last_known_player_x: f32,
        last_known_player_y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateEnemyAiArgs {
                enemy_id,
                new_state,
                position_x,
                position_y,
                velocity_x,
                velocity_y,
                target_player_id,
                last_known_player_x,
                last_known_player_y,
            },
            callback,
        )
    }
}
