// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateProjectilesArgs {
    pub delta_time: f32,
}

impl From<UpdateProjectilesArgs> for super::Reducer {
    fn from(args: UpdateProjectilesArgs) -> Self {
        Self::UpdateProjectiles {
            delta_time: args.delta_time,
        }
    }
}

impl __sdk::InModule for UpdateProjectilesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_projectiles`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_projectiles {
    /// Request that the remote module invoke the reducer `update_projectiles` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_projectiles:update_projectiles_then`] to run a callback after the reducer completes.
    fn update_projectiles(&self, delta_time: f32) -> __sdk::Result<()> {
        self.update_projectiles_then(delta_time, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_projectiles` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_projectiles_then(
        &self,
        delta_time: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_projectiles for super::RemoteReducers {
    fn update_projectiles_then(
        &self,
        delta_time: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateProjectilesArgs { delta_time }, callback)
    }
}
