// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateResourceArgs {
    pub key_id: String,
    pub new_data: String,
}

impl From<UpdateResourceArgs> for super::Reducer {
    fn from(args: UpdateResourceArgs) -> Self {
        Self::UpdateResource {
            key_id: args.key_id,
            new_data: args.new_data,
        }
    }
}

impl __sdk::InModule for UpdateResourceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_resource`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_resource {
    /// Request that the remote module invoke the reducer `update_resource` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_resource:update_resource_then`] to run a callback after the reducer completes.
    fn update_resource(&self, key_id: String, new_data: String) -> __sdk::Result<()> {
        self.update_resource_then(key_id, new_data, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_resource` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_resource_then(
        &self,
        key_id: String,
        new_data: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_resource for super::RemoteReducers {
    fn update_resource_then(
        &self,
        key_id: String,
        new_data: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateResourceArgs { key_id, new_data }, callback)
    }
}
