// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UseHealthConsumableArgs {
    pub player_id: u32,
    pub item_id: String,
}

impl From<UseHealthConsumableArgs> for super::Reducer {
    fn from(args: UseHealthConsumableArgs) -> Self {
        Self::UseHealthConsumable {
            player_id: args.player_id,
            item_id: args.item_id,
        }
    }
}

impl __sdk::InModule for UseHealthConsumableArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `use_health_consumable`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait use_health_consumable {
    /// Request that the remote module invoke the reducer `use_health_consumable` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`use_health_consumable:use_health_consumable_then`] to run a callback after the reducer completes.
    fn use_health_consumable(&self, player_id: u32, item_id: String) -> __sdk::Result<()> {
        self.use_health_consumable_then(player_id, item_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `use_health_consumable` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn use_health_consumable_then(
        &self,
        player_id: u32,
        item_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl use_health_consumable for super::RemoteReducers {
    fn use_health_consumable_then(
        &self,
        player_id: u32,
        item_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UseHealthConsumableArgs { player_id, item_id }, callback)
    }
}
