// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::world_mutation_type::WorldMutation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_mutation`.
///
/// Obtain a handle from the [`WorldMutationTableAccess::world_mutation`] method on [`super::RemoteTables`],
/// like `ctx.db.world_mutation()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_mutation().on_insert(...)`.
pub struct WorldMutationTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldMutation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_mutation`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldMutationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldMutationTableHandle`], which mediates access to the table `world_mutation`.
    fn world_mutation(&self) -> WorldMutationTableHandle<'_>;
}

impl WorldMutationTableAccess for super::RemoteTables {
    fn world_mutation(&self) -> WorldMutationTableHandle<'_> {
        WorldMutationTableHandle {
            imp: self.imp.get_table::<WorldMutation>("world_mutation"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldMutationInsertCallbackId(__sdk::CallbackId);
pub struct WorldMutationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorldMutationTableHandle<'ctx> {
    type Row = WorldMutation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldMutation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldMutationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldMutationInsertCallbackId {
        WorldMutationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldMutationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldMutationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldMutationDeleteCallbackId {
        WorldMutationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldMutationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorldMutationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldMutationTableHandle<'ctx> {
    type UpdateCallbackId = WorldMutationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldMutationUpdateCallbackId {
        WorldMutationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldMutationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `world_mutation`,
/// which allows point queries on the field of the same name
/// via the [`WorldMutationIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_mutation().id().find(...)`.
pub struct WorldMutationIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldMutation, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldMutationTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `world_mutation`.
    pub fn id(&self) -> WorldMutationIdUnique<'ctx> {
        WorldMutationIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldMutationIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WorldMutation> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldMutation>("world_mutation");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorldMutation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldMutation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorldMutation`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait world_mutationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorldMutation`.
    fn world_mutation(&self) -> __sdk::__query_builder::Table<WorldMutation>;
}

impl world_mutationQueryTableAccess for __sdk::QueryTableAccessor {
    fn world_mutation(&self) -> __sdk::__query_builder::Table<WorldMutation> {
        __sdk::__query_builder::Table::new("world_mutation")
    }
}
